#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_PingListCommandSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
using Unity.Burst;
using Unity.Burst.Intrinsics;
using Unity.Assertions;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp_Generated
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    [BurstCompile]
    internal struct Assembly_CSharp_Generated_PingListSerializer : IComponentData, IRpcCommandSerializer<PingList>
    {
        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in PingList data)
        {
            writer.WriteShort((short)data.length);
            writer.WriteInt((int) data.player0.player0.playerID);
            writer.WriteInt((int) data.player0.player0.ping);
            writer.WriteInt((int) data.player0.player1.playerID);
            writer.WriteInt((int) data.player0.player1.ping);
            writer.WriteInt((int) data.player0.player2.playerID);
            writer.WriteInt((int) data.player0.player2.ping);
            writer.WriteInt((int) data.player0.player3.playerID);
            writer.WriteInt((int) data.player0.player3.ping);
            writer.WriteInt((int) data.player0.player4.playerID);
            writer.WriteInt((int) data.player0.player4.ping);
            writer.WriteInt((int) data.player0.player5.playerID);
            writer.WriteInt((int) data.player0.player5.ping);
            writer.WriteInt((int) data.player0.player6.playerID);
            writer.WriteInt((int) data.player0.player6.ping);
            writer.WriteInt((int) data.player0.player7.playerID);
            writer.WriteInt((int) data.player0.player7.ping);
            writer.WriteInt((int) data.player0.player8.playerID);
            writer.WriteInt((int) data.player0.player8.ping);
            writer.WriteInt((int) data.player0.player9.playerID);
            writer.WriteInt((int) data.player0.player9.ping);
            writer.WriteInt((int) data.player1.player0.playerID);
            writer.WriteInt((int) data.player1.player0.ping);
            writer.WriteInt((int) data.player1.player1.playerID);
            writer.WriteInt((int) data.player1.player1.ping);
            writer.WriteInt((int) data.player1.player2.playerID);
            writer.WriteInt((int) data.player1.player2.ping);
            writer.WriteInt((int) data.player1.player3.playerID);
            writer.WriteInt((int) data.player1.player3.ping);
            writer.WriteInt((int) data.player1.player4.playerID);
            writer.WriteInt((int) data.player1.player4.ping);
            writer.WriteInt((int) data.player1.player5.playerID);
            writer.WriteInt((int) data.player1.player5.ping);
            writer.WriteInt((int) data.player1.player6.playerID);
            writer.WriteInt((int) data.player1.player6.ping);
            writer.WriteInt((int) data.player1.player7.playerID);
            writer.WriteInt((int) data.player1.player7.ping);
            writer.WriteInt((int) data.player1.player8.playerID);
            writer.WriteInt((int) data.player1.player8.ping);
            writer.WriteInt((int) data.player1.player9.playerID);
            writer.WriteInt((int) data.player1.player9.ping);
            writer.WriteInt((int) data.player2.player0.playerID);
            writer.WriteInt((int) data.player2.player0.ping);
            writer.WriteInt((int) data.player2.player1.playerID);
            writer.WriteInt((int) data.player2.player1.ping);
            writer.WriteInt((int) data.player2.player2.playerID);
            writer.WriteInt((int) data.player2.player2.ping);
            writer.WriteInt((int) data.player2.player3.playerID);
            writer.WriteInt((int) data.player2.player3.ping);
            writer.WriteInt((int) data.player2.player4.playerID);
            writer.WriteInt((int) data.player2.player4.ping);
            writer.WriteInt((int) data.player2.player5.playerID);
            writer.WriteInt((int) data.player2.player5.ping);
            writer.WriteInt((int) data.player2.player6.playerID);
            writer.WriteInt((int) data.player2.player6.ping);
            writer.WriteInt((int) data.player2.player7.playerID);
            writer.WriteInt((int) data.player2.player7.ping);
            writer.WriteInt((int) data.player2.player8.playerID);
            writer.WriteInt((int) data.player2.player8.ping);
            writer.WriteInt((int) data.player2.player9.playerID);
            writer.WriteInt((int) data.player2.player9.ping);
            writer.WriteInt((int) data.player3.player0.playerID);
            writer.WriteInt((int) data.player3.player0.ping);
            writer.WriteInt((int) data.player3.player1.playerID);
            writer.WriteInt((int) data.player3.player1.ping);
            writer.WriteInt((int) data.player3.player2.playerID);
            writer.WriteInt((int) data.player3.player2.ping);
            writer.WriteInt((int) data.player3.player3.playerID);
            writer.WriteInt((int) data.player3.player3.ping);
            writer.WriteInt((int) data.player3.player4.playerID);
            writer.WriteInt((int) data.player3.player4.ping);
            writer.WriteInt((int) data.player3.player5.playerID);
            writer.WriteInt((int) data.player3.player5.ping);
            writer.WriteInt((int) data.player3.player6.playerID);
            writer.WriteInt((int) data.player3.player6.ping);
            writer.WriteInt((int) data.player3.player7.playerID);
            writer.WriteInt((int) data.player3.player7.ping);
            writer.WriteInt((int) data.player3.player8.playerID);
            writer.WriteInt((int) data.player3.player8.ping);
            writer.WriteInt((int) data.player3.player9.playerID);
            writer.WriteInt((int) data.player3.player9.ping);
            writer.WriteInt((int) data.player4.player0.playerID);
            writer.WriteInt((int) data.player4.player0.ping);
            writer.WriteInt((int) data.player4.player1.playerID);
            writer.WriteInt((int) data.player4.player1.ping);
            writer.WriteInt((int) data.player4.player2.playerID);
            writer.WriteInt((int) data.player4.player2.ping);
            writer.WriteInt((int) data.player4.player3.playerID);
            writer.WriteInt((int) data.player4.player3.ping);
            writer.WriteInt((int) data.player4.player4.playerID);
            writer.WriteInt((int) data.player4.player4.ping);
            writer.WriteInt((int) data.player4.player5.playerID);
            writer.WriteInt((int) data.player4.player5.ping);
            writer.WriteInt((int) data.player4.player6.playerID);
            writer.WriteInt((int) data.player4.player6.ping);
            writer.WriteInt((int) data.player4.player7.playerID);
            writer.WriteInt((int) data.player4.player7.ping);
            writer.WriteInt((int) data.player4.player8.playerID);
            writer.WriteInt((int) data.player4.player8.ping);
            writer.WriteInt((int) data.player4.player9.playerID);
            writer.WriteInt((int) data.player4.player9.ping);
            writer.WriteInt((int) data.player5.player0.playerID);
            writer.WriteInt((int) data.player5.player0.ping);
            writer.WriteInt((int) data.player5.player1.playerID);
            writer.WriteInt((int) data.player5.player1.ping);
            writer.WriteInt((int) data.player5.player2.playerID);
            writer.WriteInt((int) data.player5.player2.ping);
            writer.WriteInt((int) data.player5.player3.playerID);
            writer.WriteInt((int) data.player5.player3.ping);
            writer.WriteInt((int) data.player5.player4.playerID);
            writer.WriteInt((int) data.player5.player4.ping);
            writer.WriteInt((int) data.player5.player5.playerID);
            writer.WriteInt((int) data.player5.player5.ping);
            writer.WriteInt((int) data.player5.player6.playerID);
            writer.WriteInt((int) data.player5.player6.ping);
            writer.WriteInt((int) data.player5.player7.playerID);
            writer.WriteInt((int) data.player5.player7.ping);
            writer.WriteInt((int) data.player5.player8.playerID);
            writer.WriteInt((int) data.player5.player8.ping);
            writer.WriteInt((int) data.player5.player9.playerID);
            writer.WriteInt((int) data.player5.player9.ping);
            writer.WriteInt((int) data.player6.player0.playerID);
            writer.WriteInt((int) data.player6.player0.ping);
            writer.WriteInt((int) data.player6.player1.playerID);
            writer.WriteInt((int) data.player6.player1.ping);
            writer.WriteInt((int) data.player6.player2.playerID);
            writer.WriteInt((int) data.player6.player2.ping);
            writer.WriteInt((int) data.player6.player3.playerID);
            writer.WriteInt((int) data.player6.player3.ping);
            writer.WriteInt((int) data.player6.player4.playerID);
            writer.WriteInt((int) data.player6.player4.ping);
            writer.WriteInt((int) data.player6.player5.playerID);
            writer.WriteInt((int) data.player6.player5.ping);
            writer.WriteInt((int) data.player6.player6.playerID);
            writer.WriteInt((int) data.player6.player6.ping);
            writer.WriteInt((int) data.player6.player7.playerID);
            writer.WriteInt((int) data.player6.player7.ping);
            writer.WriteInt((int) data.player6.player8.playerID);
            writer.WriteInt((int) data.player6.player8.ping);
            writer.WriteInt((int) data.player6.player9.playerID);
            writer.WriteInt((int) data.player6.player9.ping);
            writer.WriteInt((int) data.player7.player0.playerID);
            writer.WriteInt((int) data.player7.player0.ping);
            writer.WriteInt((int) data.player7.player1.playerID);
            writer.WriteInt((int) data.player7.player1.ping);
            writer.WriteInt((int) data.player7.player2.playerID);
            writer.WriteInt((int) data.player7.player2.ping);
            writer.WriteInt((int) data.player7.player3.playerID);
            writer.WriteInt((int) data.player7.player3.ping);
            writer.WriteInt((int) data.player7.player4.playerID);
            writer.WriteInt((int) data.player7.player4.ping);
            writer.WriteInt((int) data.player7.player5.playerID);
            writer.WriteInt((int) data.player7.player5.ping);
            writer.WriteInt((int) data.player7.player6.playerID);
            writer.WriteInt((int) data.player7.player6.ping);
            writer.WriteInt((int) data.player7.player7.playerID);
            writer.WriteInt((int) data.player7.player7.ping);
            writer.WriteInt((int) data.player7.player8.playerID);
            writer.WriteInt((int) data.player7.player8.ping);
            writer.WriteInt((int) data.player7.player9.playerID);
            writer.WriteInt((int) data.player7.player9.ping);
            writer.WriteInt((int) data.player8.player0.playerID);
            writer.WriteInt((int) data.player8.player0.ping);
            writer.WriteInt((int) data.player8.player1.playerID);
            writer.WriteInt((int) data.player8.player1.ping);
            writer.WriteInt((int) data.player8.player2.playerID);
            writer.WriteInt((int) data.player8.player2.ping);
            writer.WriteInt((int) data.player8.player3.playerID);
            writer.WriteInt((int) data.player8.player3.ping);
            writer.WriteInt((int) data.player8.player4.playerID);
            writer.WriteInt((int) data.player8.player4.ping);
            writer.WriteInt((int) data.player8.player5.playerID);
            writer.WriteInt((int) data.player8.player5.ping);
            writer.WriteInt((int) data.player8.player6.playerID);
            writer.WriteInt((int) data.player8.player6.ping);
            writer.WriteInt((int) data.player8.player7.playerID);
            writer.WriteInt((int) data.player8.player7.ping);
            writer.WriteInt((int) data.player8.player8.playerID);
            writer.WriteInt((int) data.player8.player8.ping);
            writer.WriteInt((int) data.player8.player9.playerID);
            writer.WriteInt((int) data.player8.player9.ping);
            writer.WriteInt((int) data.player9.player0.playerID);
            writer.WriteInt((int) data.player9.player0.ping);
            writer.WriteInt((int) data.player9.player1.playerID);
            writer.WriteInt((int) data.player9.player1.ping);
            writer.WriteInt((int) data.player9.player2.playerID);
            writer.WriteInt((int) data.player9.player2.ping);
            writer.WriteInt((int) data.player9.player3.playerID);
            writer.WriteInt((int) data.player9.player3.ping);
            writer.WriteInt((int) data.player9.player4.playerID);
            writer.WriteInt((int) data.player9.player4.ping);
            writer.WriteInt((int) data.player9.player5.playerID);
            writer.WriteInt((int) data.player9.player5.ping);
            writer.WriteInt((int) data.player9.player6.playerID);
            writer.WriteInt((int) data.player9.player6.ping);
            writer.WriteInt((int) data.player9.player7.playerID);
            writer.WriteInt((int) data.player9.player7.ping);
            writer.WriteInt((int) data.player9.player8.playerID);
            writer.WriteInt((int) data.player9.player8.ping);
            writer.WriteInt((int) data.player9.player9.playerID);
            writer.WriteInt((int) data.player9.player9.ping);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state, ref PingList data)
        {
            data.length = (short)reader.ReadShort();
            data.player0.player0.playerID = (int) reader.ReadInt();
            data.player0.player0.ping = (int) reader.ReadInt();
            data.player0.player1.playerID = (int) reader.ReadInt();
            data.player0.player1.ping = (int) reader.ReadInt();
            data.player0.player2.playerID = (int) reader.ReadInt();
            data.player0.player2.ping = (int) reader.ReadInt();
            data.player0.player3.playerID = (int) reader.ReadInt();
            data.player0.player3.ping = (int) reader.ReadInt();
            data.player0.player4.playerID = (int) reader.ReadInt();
            data.player0.player4.ping = (int) reader.ReadInt();
            data.player0.player5.playerID = (int) reader.ReadInt();
            data.player0.player5.ping = (int) reader.ReadInt();
            data.player0.player6.playerID = (int) reader.ReadInt();
            data.player0.player6.ping = (int) reader.ReadInt();
            data.player0.player7.playerID = (int) reader.ReadInt();
            data.player0.player7.ping = (int) reader.ReadInt();
            data.player0.player8.playerID = (int) reader.ReadInt();
            data.player0.player8.ping = (int) reader.ReadInt();
            data.player0.player9.playerID = (int) reader.ReadInt();
            data.player0.player9.ping = (int) reader.ReadInt();
            data.player1.player0.playerID = (int) reader.ReadInt();
            data.player1.player0.ping = (int) reader.ReadInt();
            data.player1.player1.playerID = (int) reader.ReadInt();
            data.player1.player1.ping = (int) reader.ReadInt();
            data.player1.player2.playerID = (int) reader.ReadInt();
            data.player1.player2.ping = (int) reader.ReadInt();
            data.player1.player3.playerID = (int) reader.ReadInt();
            data.player1.player3.ping = (int) reader.ReadInt();
            data.player1.player4.playerID = (int) reader.ReadInt();
            data.player1.player4.ping = (int) reader.ReadInt();
            data.player1.player5.playerID = (int) reader.ReadInt();
            data.player1.player5.ping = (int) reader.ReadInt();
            data.player1.player6.playerID = (int) reader.ReadInt();
            data.player1.player6.ping = (int) reader.ReadInt();
            data.player1.player7.playerID = (int) reader.ReadInt();
            data.player1.player7.ping = (int) reader.ReadInt();
            data.player1.player8.playerID = (int) reader.ReadInt();
            data.player1.player8.ping = (int) reader.ReadInt();
            data.player1.player9.playerID = (int) reader.ReadInt();
            data.player1.player9.ping = (int) reader.ReadInt();
            data.player2.player0.playerID = (int) reader.ReadInt();
            data.player2.player0.ping = (int) reader.ReadInt();
            data.player2.player1.playerID = (int) reader.ReadInt();
            data.player2.player1.ping = (int) reader.ReadInt();
            data.player2.player2.playerID = (int) reader.ReadInt();
            data.player2.player2.ping = (int) reader.ReadInt();
            data.player2.player3.playerID = (int) reader.ReadInt();
            data.player2.player3.ping = (int) reader.ReadInt();
            data.player2.player4.playerID = (int) reader.ReadInt();
            data.player2.player4.ping = (int) reader.ReadInt();
            data.player2.player5.playerID = (int) reader.ReadInt();
            data.player2.player5.ping = (int) reader.ReadInt();
            data.player2.player6.playerID = (int) reader.ReadInt();
            data.player2.player6.ping = (int) reader.ReadInt();
            data.player2.player7.playerID = (int) reader.ReadInt();
            data.player2.player7.ping = (int) reader.ReadInt();
            data.player2.player8.playerID = (int) reader.ReadInt();
            data.player2.player8.ping = (int) reader.ReadInt();
            data.player2.player9.playerID = (int) reader.ReadInt();
            data.player2.player9.ping = (int) reader.ReadInt();
            data.player3.player0.playerID = (int) reader.ReadInt();
            data.player3.player0.ping = (int) reader.ReadInt();
            data.player3.player1.playerID = (int) reader.ReadInt();
            data.player3.player1.ping = (int) reader.ReadInt();
            data.player3.player2.playerID = (int) reader.ReadInt();
            data.player3.player2.ping = (int) reader.ReadInt();
            data.player3.player3.playerID = (int) reader.ReadInt();
            data.player3.player3.ping = (int) reader.ReadInt();
            data.player3.player4.playerID = (int) reader.ReadInt();
            data.player3.player4.ping = (int) reader.ReadInt();
            data.player3.player5.playerID = (int) reader.ReadInt();
            data.player3.player5.ping = (int) reader.ReadInt();
            data.player3.player6.playerID = (int) reader.ReadInt();
            data.player3.player6.ping = (int) reader.ReadInt();
            data.player3.player7.playerID = (int) reader.ReadInt();
            data.player3.player7.ping = (int) reader.ReadInt();
            data.player3.player8.playerID = (int) reader.ReadInt();
            data.player3.player8.ping = (int) reader.ReadInt();
            data.player3.player9.playerID = (int) reader.ReadInt();
            data.player3.player9.ping = (int) reader.ReadInt();
            data.player4.player0.playerID = (int) reader.ReadInt();
            data.player4.player0.ping = (int) reader.ReadInt();
            data.player4.player1.playerID = (int) reader.ReadInt();
            data.player4.player1.ping = (int) reader.ReadInt();
            data.player4.player2.playerID = (int) reader.ReadInt();
            data.player4.player2.ping = (int) reader.ReadInt();
            data.player4.player3.playerID = (int) reader.ReadInt();
            data.player4.player3.ping = (int) reader.ReadInt();
            data.player4.player4.playerID = (int) reader.ReadInt();
            data.player4.player4.ping = (int) reader.ReadInt();
            data.player4.player5.playerID = (int) reader.ReadInt();
            data.player4.player5.ping = (int) reader.ReadInt();
            data.player4.player6.playerID = (int) reader.ReadInt();
            data.player4.player6.ping = (int) reader.ReadInt();
            data.player4.player7.playerID = (int) reader.ReadInt();
            data.player4.player7.ping = (int) reader.ReadInt();
            data.player4.player8.playerID = (int) reader.ReadInt();
            data.player4.player8.ping = (int) reader.ReadInt();
            data.player4.player9.playerID = (int) reader.ReadInt();
            data.player4.player9.ping = (int) reader.ReadInt();
            data.player5.player0.playerID = (int) reader.ReadInt();
            data.player5.player0.ping = (int) reader.ReadInt();
            data.player5.player1.playerID = (int) reader.ReadInt();
            data.player5.player1.ping = (int) reader.ReadInt();
            data.player5.player2.playerID = (int) reader.ReadInt();
            data.player5.player2.ping = (int) reader.ReadInt();
            data.player5.player3.playerID = (int) reader.ReadInt();
            data.player5.player3.ping = (int) reader.ReadInt();
            data.player5.player4.playerID = (int) reader.ReadInt();
            data.player5.player4.ping = (int) reader.ReadInt();
            data.player5.player5.playerID = (int) reader.ReadInt();
            data.player5.player5.ping = (int) reader.ReadInt();
            data.player5.player6.playerID = (int) reader.ReadInt();
            data.player5.player6.ping = (int) reader.ReadInt();
            data.player5.player7.playerID = (int) reader.ReadInt();
            data.player5.player7.ping = (int) reader.ReadInt();
            data.player5.player8.playerID = (int) reader.ReadInt();
            data.player5.player8.ping = (int) reader.ReadInt();
            data.player5.player9.playerID = (int) reader.ReadInt();
            data.player5.player9.ping = (int) reader.ReadInt();
            data.player6.player0.playerID = (int) reader.ReadInt();
            data.player6.player0.ping = (int) reader.ReadInt();
            data.player6.player1.playerID = (int) reader.ReadInt();
            data.player6.player1.ping = (int) reader.ReadInt();
            data.player6.player2.playerID = (int) reader.ReadInt();
            data.player6.player2.ping = (int) reader.ReadInt();
            data.player6.player3.playerID = (int) reader.ReadInt();
            data.player6.player3.ping = (int) reader.ReadInt();
            data.player6.player4.playerID = (int) reader.ReadInt();
            data.player6.player4.ping = (int) reader.ReadInt();
            data.player6.player5.playerID = (int) reader.ReadInt();
            data.player6.player5.ping = (int) reader.ReadInt();
            data.player6.player6.playerID = (int) reader.ReadInt();
            data.player6.player6.ping = (int) reader.ReadInt();
            data.player6.player7.playerID = (int) reader.ReadInt();
            data.player6.player7.ping = (int) reader.ReadInt();
            data.player6.player8.playerID = (int) reader.ReadInt();
            data.player6.player8.ping = (int) reader.ReadInt();
            data.player6.player9.playerID = (int) reader.ReadInt();
            data.player6.player9.ping = (int) reader.ReadInt();
            data.player7.player0.playerID = (int) reader.ReadInt();
            data.player7.player0.ping = (int) reader.ReadInt();
            data.player7.player1.playerID = (int) reader.ReadInt();
            data.player7.player1.ping = (int) reader.ReadInt();
            data.player7.player2.playerID = (int) reader.ReadInt();
            data.player7.player2.ping = (int) reader.ReadInt();
            data.player7.player3.playerID = (int) reader.ReadInt();
            data.player7.player3.ping = (int) reader.ReadInt();
            data.player7.player4.playerID = (int) reader.ReadInt();
            data.player7.player4.ping = (int) reader.ReadInt();
            data.player7.player5.playerID = (int) reader.ReadInt();
            data.player7.player5.ping = (int) reader.ReadInt();
            data.player7.player6.playerID = (int) reader.ReadInt();
            data.player7.player6.ping = (int) reader.ReadInt();
            data.player7.player7.playerID = (int) reader.ReadInt();
            data.player7.player7.ping = (int) reader.ReadInt();
            data.player7.player8.playerID = (int) reader.ReadInt();
            data.player7.player8.ping = (int) reader.ReadInt();
            data.player7.player9.playerID = (int) reader.ReadInt();
            data.player7.player9.ping = (int) reader.ReadInt();
            data.player8.player0.playerID = (int) reader.ReadInt();
            data.player8.player0.ping = (int) reader.ReadInt();
            data.player8.player1.playerID = (int) reader.ReadInt();
            data.player8.player1.ping = (int) reader.ReadInt();
            data.player8.player2.playerID = (int) reader.ReadInt();
            data.player8.player2.ping = (int) reader.ReadInt();
            data.player8.player3.playerID = (int) reader.ReadInt();
            data.player8.player3.ping = (int) reader.ReadInt();
            data.player8.player4.playerID = (int) reader.ReadInt();
            data.player8.player4.ping = (int) reader.ReadInt();
            data.player8.player5.playerID = (int) reader.ReadInt();
            data.player8.player5.ping = (int) reader.ReadInt();
            data.player8.player6.playerID = (int) reader.ReadInt();
            data.player8.player6.ping = (int) reader.ReadInt();
            data.player8.player7.playerID = (int) reader.ReadInt();
            data.player8.player7.ping = (int) reader.ReadInt();
            data.player8.player8.playerID = (int) reader.ReadInt();
            data.player8.player8.ping = (int) reader.ReadInt();
            data.player8.player9.playerID = (int) reader.ReadInt();
            data.player8.player9.ping = (int) reader.ReadInt();
            data.player9.player0.playerID = (int) reader.ReadInt();
            data.player9.player0.ping = (int) reader.ReadInt();
            data.player9.player1.playerID = (int) reader.ReadInt();
            data.player9.player1.ping = (int) reader.ReadInt();
            data.player9.player2.playerID = (int) reader.ReadInt();
            data.player9.player2.ping = (int) reader.ReadInt();
            data.player9.player3.playerID = (int) reader.ReadInt();
            data.player9.player3.ping = (int) reader.ReadInt();
            data.player9.player4.playerID = (int) reader.ReadInt();
            data.player9.player4.ping = (int) reader.ReadInt();
            data.player9.player5.playerID = (int) reader.ReadInt();
            data.player9.player5.ping = (int) reader.ReadInt();
            data.player9.player6.playerID = (int) reader.ReadInt();
            data.player9.player6.ping = (int) reader.ReadInt();
            data.player9.player7.playerID = (int) reader.ReadInt();
            data.player9.player7.ping = (int) reader.ReadInt();
            data.player9.player8.playerID = (int) reader.ReadInt();
            data.player9.player8.ping = (int) reader.ReadInt();
            data.player9.player9.playerID = (int) reader.ReadInt();
            data.player9.player9.ping = (int) reader.ReadInt();
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<Assembly_CSharp_Generated_PingListSerializer, PingList>(ref parameters);
        }

        static readonly PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }

    [System.Runtime.CompilerServices.CompilerGenerated]
    [UpdateInGroup(typeof(RpcCommandRequestSystemGroup))]
    [CreateAfter(typeof(RpcSystem))]
    [BurstCompile]
    internal partial struct Assembly_CSharp_Generated_PingListRpcCommandRequestSystem : ISystem
    {
        RpcCommandRequest<Assembly_CSharp_Generated_PingListSerializer, PingList> m_Request;
        [BurstCompile]
        struct SendRpc : IJobChunk
        {
            public RpcCommandRequest<Assembly_CSharp_Generated_PingListSerializer, PingList>.SendRpcData data;
            public void Execute(in ArchetypeChunk chunk, int unfilteredChunkIndex, bool useEnabledMask, in v128 chunkEnabledMask)
            {
                Assert.IsFalse(useEnabledMask);
                data.Execute(chunk, unfilteredChunkIndex);
            }
        }
        public void OnCreate(ref SystemState state)
        {
            m_Request.OnCreate(ref state);
        }
        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            var sendJob = new SendRpc{data = m_Request.InitJobData(ref state)};
            state.Dependency = sendJob.Schedule(m_Request.Query, state.Dependency);
        }
    }
}
