#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_FixedChunkCommandSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
using Unity.Burst;
using Unity.Burst.Intrinsics;
using Unity.Assertions;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp_Generated
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    [BurstCompile]
    internal struct Assembly_CSharp_Generated_FixedChunkSerializer : IComponentData, IRpcCommandSerializer<FixedChunk>
    {
        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in FixedChunk data)
        {
            writer.WriteFloat(data.worldPosition.x);
            writer.WriteFloat(data.worldPosition.y);
            writer.WriteInt((int) data.chunkCoordinates.x);
            writer.WriteInt((int) data.chunkCoordinates.y);
            writer.WriteInt((int) data.list0.tile0.tileID);
            writer.WriteByte((byte)data.list0.tile0.variant);
            writer.WriteInt((int) data.list0.tile1.tileID);
            writer.WriteByte((byte)data.list0.tile1.variant);
            writer.WriteInt((int) data.list0.tile2.tileID);
            writer.WriteByte((byte)data.list0.tile2.variant);
            writer.WriteInt((int) data.list0.tile3.tileID);
            writer.WriteByte((byte)data.list0.tile3.variant);
            writer.WriteInt((int) data.list0.tile4.tileID);
            writer.WriteByte((byte)data.list0.tile4.variant);
            writer.WriteInt((int) data.list0.tile5.tileID);
            writer.WriteByte((byte)data.list0.tile5.variant);
            writer.WriteInt((int) data.list0.tile6.tileID);
            writer.WriteByte((byte)data.list0.tile6.variant);
            writer.WriteInt((int) data.list0.tile7.tileID);
            writer.WriteByte((byte)data.list0.tile7.variant);
            writer.WriteInt((int) data.list0.tile8.tileID);
            writer.WriteByte((byte)data.list0.tile8.variant);
            writer.WriteInt((int) data.list0.tile9.tileID);
            writer.WriteByte((byte)data.list0.tile9.variant);
            writer.WriteInt((int) data.list1.tile0.tileID);
            writer.WriteByte((byte)data.list1.tile0.variant);
            writer.WriteInt((int) data.list1.tile1.tileID);
            writer.WriteByte((byte)data.list1.tile1.variant);
            writer.WriteInt((int) data.list1.tile2.tileID);
            writer.WriteByte((byte)data.list1.tile2.variant);
            writer.WriteInt((int) data.list1.tile3.tileID);
            writer.WriteByte((byte)data.list1.tile3.variant);
            writer.WriteInt((int) data.list1.tile4.tileID);
            writer.WriteByte((byte)data.list1.tile4.variant);
            writer.WriteInt((int) data.list1.tile5.tileID);
            writer.WriteByte((byte)data.list1.tile5.variant);
            writer.WriteInt((int) data.list1.tile6.tileID);
            writer.WriteByte((byte)data.list1.tile6.variant);
            writer.WriteInt((int) data.list1.tile7.tileID);
            writer.WriteByte((byte)data.list1.tile7.variant);
            writer.WriteInt((int) data.list1.tile8.tileID);
            writer.WriteByte((byte)data.list1.tile8.variant);
            writer.WriteInt((int) data.list1.tile9.tileID);
            writer.WriteByte((byte)data.list1.tile9.variant);
            writer.WriteInt((int) data.list2.tile0.tileID);
            writer.WriteByte((byte)data.list2.tile0.variant);
            writer.WriteInt((int) data.list2.tile1.tileID);
            writer.WriteByte((byte)data.list2.tile1.variant);
            writer.WriteInt((int) data.list2.tile2.tileID);
            writer.WriteByte((byte)data.list2.tile2.variant);
            writer.WriteInt((int) data.list2.tile3.tileID);
            writer.WriteByte((byte)data.list2.tile3.variant);
            writer.WriteInt((int) data.list2.tile4.tileID);
            writer.WriteByte((byte)data.list2.tile4.variant);
            writer.WriteInt((int) data.list2.tile5.tileID);
            writer.WriteByte((byte)data.list2.tile5.variant);
            writer.WriteInt((int) data.list2.tile6.tileID);
            writer.WriteByte((byte)data.list2.tile6.variant);
            writer.WriteInt((int) data.list2.tile7.tileID);
            writer.WriteByte((byte)data.list2.tile7.variant);
            writer.WriteInt((int) data.list2.tile8.tileID);
            writer.WriteByte((byte)data.list2.tile8.variant);
            writer.WriteInt((int) data.list2.tile9.tileID);
            writer.WriteByte((byte)data.list2.tile9.variant);
            writer.WriteInt((int) data.list3.tile0.tileID);
            writer.WriteByte((byte)data.list3.tile0.variant);
            writer.WriteInt((int) data.list3.tile1.tileID);
            writer.WriteByte((byte)data.list3.tile1.variant);
            writer.WriteInt((int) data.list3.tile2.tileID);
            writer.WriteByte((byte)data.list3.tile2.variant);
            writer.WriteInt((int) data.list3.tile3.tileID);
            writer.WriteByte((byte)data.list3.tile3.variant);
            writer.WriteInt((int) data.list3.tile4.tileID);
            writer.WriteByte((byte)data.list3.tile4.variant);
            writer.WriteInt((int) data.list3.tile5.tileID);
            writer.WriteByte((byte)data.list3.tile5.variant);
            writer.WriteInt((int) data.list3.tile6.tileID);
            writer.WriteByte((byte)data.list3.tile6.variant);
            writer.WriteInt((int) data.list3.tile7.tileID);
            writer.WriteByte((byte)data.list3.tile7.variant);
            writer.WriteInt((int) data.list3.tile8.tileID);
            writer.WriteByte((byte)data.list3.tile8.variant);
            writer.WriteInt((int) data.list3.tile9.tileID);
            writer.WriteByte((byte)data.list3.tile9.variant);
            writer.WriteInt((int) data.list4.tile0.tileID);
            writer.WriteByte((byte)data.list4.tile0.variant);
            writer.WriteInt((int) data.list4.tile1.tileID);
            writer.WriteByte((byte)data.list4.tile1.variant);
            writer.WriteInt((int) data.list4.tile2.tileID);
            writer.WriteByte((byte)data.list4.tile2.variant);
            writer.WriteInt((int) data.list4.tile3.tileID);
            writer.WriteByte((byte)data.list4.tile3.variant);
            writer.WriteInt((int) data.list4.tile4.tileID);
            writer.WriteByte((byte)data.list4.tile4.variant);
            writer.WriteInt((int) data.list4.tile5.tileID);
            writer.WriteByte((byte)data.list4.tile5.variant);
            writer.WriteInt((int) data.list4.tile6.tileID);
            writer.WriteByte((byte)data.list4.tile6.variant);
            writer.WriteInt((int) data.list4.tile7.tileID);
            writer.WriteByte((byte)data.list4.tile7.variant);
            writer.WriteInt((int) data.list4.tile8.tileID);
            writer.WriteByte((byte)data.list4.tile8.variant);
            writer.WriteInt((int) data.list4.tile9.tileID);
            writer.WriteByte((byte)data.list4.tile9.variant);
            writer.WriteInt((int) data.list5.tile0.tileID);
            writer.WriteByte((byte)data.list5.tile0.variant);
            writer.WriteInt((int) data.list5.tile1.tileID);
            writer.WriteByte((byte)data.list5.tile1.variant);
            writer.WriteInt((int) data.list5.tile2.tileID);
            writer.WriteByte((byte)data.list5.tile2.variant);
            writer.WriteInt((int) data.list5.tile3.tileID);
            writer.WriteByte((byte)data.list5.tile3.variant);
            writer.WriteInt((int) data.list5.tile4.tileID);
            writer.WriteByte((byte)data.list5.tile4.variant);
            writer.WriteInt((int) data.list5.tile5.tileID);
            writer.WriteByte((byte)data.list5.tile5.variant);
            writer.WriteInt((int) data.list5.tile6.tileID);
            writer.WriteByte((byte)data.list5.tile6.variant);
            writer.WriteInt((int) data.list5.tile7.tileID);
            writer.WriteByte((byte)data.list5.tile7.variant);
            writer.WriteInt((int) data.list5.tile8.tileID);
            writer.WriteByte((byte)data.list5.tile8.variant);
            writer.WriteInt((int) data.list5.tile9.tileID);
            writer.WriteByte((byte)data.list5.tile9.variant);
            writer.WriteInt((int) data.list6.tile0.tileID);
            writer.WriteByte((byte)data.list6.tile0.variant);
            writer.WriteInt((int) data.list6.tile1.tileID);
            writer.WriteByte((byte)data.list6.tile1.variant);
            writer.WriteInt((int) data.list6.tile2.tileID);
            writer.WriteByte((byte)data.list6.tile2.variant);
            writer.WriteInt((int) data.list6.tile3.tileID);
            writer.WriteByte((byte)data.list6.tile3.variant);
            writer.WriteInt((int) data.list6.tile4.tileID);
            writer.WriteByte((byte)data.list6.tile4.variant);
            writer.WriteInt((int) data.list6.tile5.tileID);
            writer.WriteByte((byte)data.list6.tile5.variant);
            writer.WriteInt((int) data.list6.tile6.tileID);
            writer.WriteByte((byte)data.list6.tile6.variant);
            writer.WriteInt((int) data.list6.tile7.tileID);
            writer.WriteByte((byte)data.list6.tile7.variant);
            writer.WriteInt((int) data.list6.tile8.tileID);
            writer.WriteByte((byte)data.list6.tile8.variant);
            writer.WriteInt((int) data.list6.tile9.tileID);
            writer.WriteByte((byte)data.list6.tile9.variant);
            writer.WriteInt((int) data.list7.tile0.tileID);
            writer.WriteByte((byte)data.list7.tile0.variant);
            writer.WriteInt((int) data.list7.tile1.tileID);
            writer.WriteByte((byte)data.list7.tile1.variant);
            writer.WriteInt((int) data.list7.tile2.tileID);
            writer.WriteByte((byte)data.list7.tile2.variant);
            writer.WriteInt((int) data.list7.tile3.tileID);
            writer.WriteByte((byte)data.list7.tile3.variant);
            writer.WriteInt((int) data.list7.tile4.tileID);
            writer.WriteByte((byte)data.list7.tile4.variant);
            writer.WriteInt((int) data.list7.tile5.tileID);
            writer.WriteByte((byte)data.list7.tile5.variant);
            writer.WriteInt((int) data.list7.tile6.tileID);
            writer.WriteByte((byte)data.list7.tile6.variant);
            writer.WriteInt((int) data.list7.tile7.tileID);
            writer.WriteByte((byte)data.list7.tile7.variant);
            writer.WriteInt((int) data.list7.tile8.tileID);
            writer.WriteByte((byte)data.list7.tile8.variant);
            writer.WriteInt((int) data.list7.tile9.tileID);
            writer.WriteByte((byte)data.list7.tile9.variant);
            writer.WriteInt((int) data.list8.tile0.tileID);
            writer.WriteByte((byte)data.list8.tile0.variant);
            writer.WriteInt((int) data.list8.tile1.tileID);
            writer.WriteByte((byte)data.list8.tile1.variant);
            writer.WriteInt((int) data.list8.tile2.tileID);
            writer.WriteByte((byte)data.list8.tile2.variant);
            writer.WriteInt((int) data.list8.tile3.tileID);
            writer.WriteByte((byte)data.list8.tile3.variant);
            writer.WriteInt((int) data.list8.tile4.tileID);
            writer.WriteByte((byte)data.list8.tile4.variant);
            writer.WriteInt((int) data.list8.tile5.tileID);
            writer.WriteByte((byte)data.list8.tile5.variant);
            writer.WriteInt((int) data.list8.tile6.tileID);
            writer.WriteByte((byte)data.list8.tile6.variant);
            writer.WriteInt((int) data.list8.tile7.tileID);
            writer.WriteByte((byte)data.list8.tile7.variant);
            writer.WriteInt((int) data.list8.tile8.tileID);
            writer.WriteByte((byte)data.list8.tile8.variant);
            writer.WriteInt((int) data.list8.tile9.tileID);
            writer.WriteByte((byte)data.list8.tile9.variant);
            writer.WriteInt((int) data.list9.tile0.tileID);
            writer.WriteByte((byte)data.list9.tile0.variant);
            writer.WriteInt((int) data.list9.tile1.tileID);
            writer.WriteByte((byte)data.list9.tile1.variant);
            writer.WriteInt((int) data.list9.tile2.tileID);
            writer.WriteByte((byte)data.list9.tile2.variant);
            writer.WriteInt((int) data.list9.tile3.tileID);
            writer.WriteByte((byte)data.list9.tile3.variant);
            writer.WriteInt((int) data.list9.tile4.tileID);
            writer.WriteByte((byte)data.list9.tile4.variant);
            writer.WriteInt((int) data.list9.tile5.tileID);
            writer.WriteByte((byte)data.list9.tile5.variant);
            writer.WriteInt((int) data.list9.tile6.tileID);
            writer.WriteByte((byte)data.list9.tile6.variant);
            writer.WriteInt((int) data.list9.tile7.tileID);
            writer.WriteByte((byte)data.list9.tile7.variant);
            writer.WriteInt((int) data.list9.tile8.tileID);
            writer.WriteByte((byte)data.list9.tile8.variant);
            writer.WriteInt((int) data.list9.tile9.tileID);
            writer.WriteByte((byte)data.list9.tile9.variant);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state, ref FixedChunk data)
        {
            data.worldPosition.x = reader.ReadFloat();
            data.worldPosition.y = reader.ReadFloat();
            data.chunkCoordinates.x = (int) reader.ReadInt();
            data.chunkCoordinates.y = (int) reader.ReadInt();
            data.list0.tile0.tileID = (int) reader.ReadInt();
            data.list0.tile0.variant = (byte)reader.ReadByte();
            data.list0.tile1.tileID = (int) reader.ReadInt();
            data.list0.tile1.variant = (byte)reader.ReadByte();
            data.list0.tile2.tileID = (int) reader.ReadInt();
            data.list0.tile2.variant = (byte)reader.ReadByte();
            data.list0.tile3.tileID = (int) reader.ReadInt();
            data.list0.tile3.variant = (byte)reader.ReadByte();
            data.list0.tile4.tileID = (int) reader.ReadInt();
            data.list0.tile4.variant = (byte)reader.ReadByte();
            data.list0.tile5.tileID = (int) reader.ReadInt();
            data.list0.tile5.variant = (byte)reader.ReadByte();
            data.list0.tile6.tileID = (int) reader.ReadInt();
            data.list0.tile6.variant = (byte)reader.ReadByte();
            data.list0.tile7.tileID = (int) reader.ReadInt();
            data.list0.tile7.variant = (byte)reader.ReadByte();
            data.list0.tile8.tileID = (int) reader.ReadInt();
            data.list0.tile8.variant = (byte)reader.ReadByte();
            data.list0.tile9.tileID = (int) reader.ReadInt();
            data.list0.tile9.variant = (byte)reader.ReadByte();
            data.list1.tile0.tileID = (int) reader.ReadInt();
            data.list1.tile0.variant = (byte)reader.ReadByte();
            data.list1.tile1.tileID = (int) reader.ReadInt();
            data.list1.tile1.variant = (byte)reader.ReadByte();
            data.list1.tile2.tileID = (int) reader.ReadInt();
            data.list1.tile2.variant = (byte)reader.ReadByte();
            data.list1.tile3.tileID = (int) reader.ReadInt();
            data.list1.tile3.variant = (byte)reader.ReadByte();
            data.list1.tile4.tileID = (int) reader.ReadInt();
            data.list1.tile4.variant = (byte)reader.ReadByte();
            data.list1.tile5.tileID = (int) reader.ReadInt();
            data.list1.tile5.variant = (byte)reader.ReadByte();
            data.list1.tile6.tileID = (int) reader.ReadInt();
            data.list1.tile6.variant = (byte)reader.ReadByte();
            data.list1.tile7.tileID = (int) reader.ReadInt();
            data.list1.tile7.variant = (byte)reader.ReadByte();
            data.list1.tile8.tileID = (int) reader.ReadInt();
            data.list1.tile8.variant = (byte)reader.ReadByte();
            data.list1.tile9.tileID = (int) reader.ReadInt();
            data.list1.tile9.variant = (byte)reader.ReadByte();
            data.list2.tile0.tileID = (int) reader.ReadInt();
            data.list2.tile0.variant = (byte)reader.ReadByte();
            data.list2.tile1.tileID = (int) reader.ReadInt();
            data.list2.tile1.variant = (byte)reader.ReadByte();
            data.list2.tile2.tileID = (int) reader.ReadInt();
            data.list2.tile2.variant = (byte)reader.ReadByte();
            data.list2.tile3.tileID = (int) reader.ReadInt();
            data.list2.tile3.variant = (byte)reader.ReadByte();
            data.list2.tile4.tileID = (int) reader.ReadInt();
            data.list2.tile4.variant = (byte)reader.ReadByte();
            data.list2.tile5.tileID = (int) reader.ReadInt();
            data.list2.tile5.variant = (byte)reader.ReadByte();
            data.list2.tile6.tileID = (int) reader.ReadInt();
            data.list2.tile6.variant = (byte)reader.ReadByte();
            data.list2.tile7.tileID = (int) reader.ReadInt();
            data.list2.tile7.variant = (byte)reader.ReadByte();
            data.list2.tile8.tileID = (int) reader.ReadInt();
            data.list2.tile8.variant = (byte)reader.ReadByte();
            data.list2.tile9.tileID = (int) reader.ReadInt();
            data.list2.tile9.variant = (byte)reader.ReadByte();
            data.list3.tile0.tileID = (int) reader.ReadInt();
            data.list3.tile0.variant = (byte)reader.ReadByte();
            data.list3.tile1.tileID = (int) reader.ReadInt();
            data.list3.tile1.variant = (byte)reader.ReadByte();
            data.list3.tile2.tileID = (int) reader.ReadInt();
            data.list3.tile2.variant = (byte)reader.ReadByte();
            data.list3.tile3.tileID = (int) reader.ReadInt();
            data.list3.tile3.variant = (byte)reader.ReadByte();
            data.list3.tile4.tileID = (int) reader.ReadInt();
            data.list3.tile4.variant = (byte)reader.ReadByte();
            data.list3.tile5.tileID = (int) reader.ReadInt();
            data.list3.tile5.variant = (byte)reader.ReadByte();
            data.list3.tile6.tileID = (int) reader.ReadInt();
            data.list3.tile6.variant = (byte)reader.ReadByte();
            data.list3.tile7.tileID = (int) reader.ReadInt();
            data.list3.tile7.variant = (byte)reader.ReadByte();
            data.list3.tile8.tileID = (int) reader.ReadInt();
            data.list3.tile8.variant = (byte)reader.ReadByte();
            data.list3.tile9.tileID = (int) reader.ReadInt();
            data.list3.tile9.variant = (byte)reader.ReadByte();
            data.list4.tile0.tileID = (int) reader.ReadInt();
            data.list4.tile0.variant = (byte)reader.ReadByte();
            data.list4.tile1.tileID = (int) reader.ReadInt();
            data.list4.tile1.variant = (byte)reader.ReadByte();
            data.list4.tile2.tileID = (int) reader.ReadInt();
            data.list4.tile2.variant = (byte)reader.ReadByte();
            data.list4.tile3.tileID = (int) reader.ReadInt();
            data.list4.tile3.variant = (byte)reader.ReadByte();
            data.list4.tile4.tileID = (int) reader.ReadInt();
            data.list4.tile4.variant = (byte)reader.ReadByte();
            data.list4.tile5.tileID = (int) reader.ReadInt();
            data.list4.tile5.variant = (byte)reader.ReadByte();
            data.list4.tile6.tileID = (int) reader.ReadInt();
            data.list4.tile6.variant = (byte)reader.ReadByte();
            data.list4.tile7.tileID = (int) reader.ReadInt();
            data.list4.tile7.variant = (byte)reader.ReadByte();
            data.list4.tile8.tileID = (int) reader.ReadInt();
            data.list4.tile8.variant = (byte)reader.ReadByte();
            data.list4.tile9.tileID = (int) reader.ReadInt();
            data.list4.tile9.variant = (byte)reader.ReadByte();
            data.list5.tile0.tileID = (int) reader.ReadInt();
            data.list5.tile0.variant = (byte)reader.ReadByte();
            data.list5.tile1.tileID = (int) reader.ReadInt();
            data.list5.tile1.variant = (byte)reader.ReadByte();
            data.list5.tile2.tileID = (int) reader.ReadInt();
            data.list5.tile2.variant = (byte)reader.ReadByte();
            data.list5.tile3.tileID = (int) reader.ReadInt();
            data.list5.tile3.variant = (byte)reader.ReadByte();
            data.list5.tile4.tileID = (int) reader.ReadInt();
            data.list5.tile4.variant = (byte)reader.ReadByte();
            data.list5.tile5.tileID = (int) reader.ReadInt();
            data.list5.tile5.variant = (byte)reader.ReadByte();
            data.list5.tile6.tileID = (int) reader.ReadInt();
            data.list5.tile6.variant = (byte)reader.ReadByte();
            data.list5.tile7.tileID = (int) reader.ReadInt();
            data.list5.tile7.variant = (byte)reader.ReadByte();
            data.list5.tile8.tileID = (int) reader.ReadInt();
            data.list5.tile8.variant = (byte)reader.ReadByte();
            data.list5.tile9.tileID = (int) reader.ReadInt();
            data.list5.tile9.variant = (byte)reader.ReadByte();
            data.list6.tile0.tileID = (int) reader.ReadInt();
            data.list6.tile0.variant = (byte)reader.ReadByte();
            data.list6.tile1.tileID = (int) reader.ReadInt();
            data.list6.tile1.variant = (byte)reader.ReadByte();
            data.list6.tile2.tileID = (int) reader.ReadInt();
            data.list6.tile2.variant = (byte)reader.ReadByte();
            data.list6.tile3.tileID = (int) reader.ReadInt();
            data.list6.tile3.variant = (byte)reader.ReadByte();
            data.list6.tile4.tileID = (int) reader.ReadInt();
            data.list6.tile4.variant = (byte)reader.ReadByte();
            data.list6.tile5.tileID = (int) reader.ReadInt();
            data.list6.tile5.variant = (byte)reader.ReadByte();
            data.list6.tile6.tileID = (int) reader.ReadInt();
            data.list6.tile6.variant = (byte)reader.ReadByte();
            data.list6.tile7.tileID = (int) reader.ReadInt();
            data.list6.tile7.variant = (byte)reader.ReadByte();
            data.list6.tile8.tileID = (int) reader.ReadInt();
            data.list6.tile8.variant = (byte)reader.ReadByte();
            data.list6.tile9.tileID = (int) reader.ReadInt();
            data.list6.tile9.variant = (byte)reader.ReadByte();
            data.list7.tile0.tileID = (int) reader.ReadInt();
            data.list7.tile0.variant = (byte)reader.ReadByte();
            data.list7.tile1.tileID = (int) reader.ReadInt();
            data.list7.tile1.variant = (byte)reader.ReadByte();
            data.list7.tile2.tileID = (int) reader.ReadInt();
            data.list7.tile2.variant = (byte)reader.ReadByte();
            data.list7.tile3.tileID = (int) reader.ReadInt();
            data.list7.tile3.variant = (byte)reader.ReadByte();
            data.list7.tile4.tileID = (int) reader.ReadInt();
            data.list7.tile4.variant = (byte)reader.ReadByte();
            data.list7.tile5.tileID = (int) reader.ReadInt();
            data.list7.tile5.variant = (byte)reader.ReadByte();
            data.list7.tile6.tileID = (int) reader.ReadInt();
            data.list7.tile6.variant = (byte)reader.ReadByte();
            data.list7.tile7.tileID = (int) reader.ReadInt();
            data.list7.tile7.variant = (byte)reader.ReadByte();
            data.list7.tile8.tileID = (int) reader.ReadInt();
            data.list7.tile8.variant = (byte)reader.ReadByte();
            data.list7.tile9.tileID = (int) reader.ReadInt();
            data.list7.tile9.variant = (byte)reader.ReadByte();
            data.list8.tile0.tileID = (int) reader.ReadInt();
            data.list8.tile0.variant = (byte)reader.ReadByte();
            data.list8.tile1.tileID = (int) reader.ReadInt();
            data.list8.tile1.variant = (byte)reader.ReadByte();
            data.list8.tile2.tileID = (int) reader.ReadInt();
            data.list8.tile2.variant = (byte)reader.ReadByte();
            data.list8.tile3.tileID = (int) reader.ReadInt();
            data.list8.tile3.variant = (byte)reader.ReadByte();
            data.list8.tile4.tileID = (int) reader.ReadInt();
            data.list8.tile4.variant = (byte)reader.ReadByte();
            data.list8.tile5.tileID = (int) reader.ReadInt();
            data.list8.tile5.variant = (byte)reader.ReadByte();
            data.list8.tile6.tileID = (int) reader.ReadInt();
            data.list8.tile6.variant = (byte)reader.ReadByte();
            data.list8.tile7.tileID = (int) reader.ReadInt();
            data.list8.tile7.variant = (byte)reader.ReadByte();
            data.list8.tile8.tileID = (int) reader.ReadInt();
            data.list8.tile8.variant = (byte)reader.ReadByte();
            data.list8.tile9.tileID = (int) reader.ReadInt();
            data.list8.tile9.variant = (byte)reader.ReadByte();
            data.list9.tile0.tileID = (int) reader.ReadInt();
            data.list9.tile0.variant = (byte)reader.ReadByte();
            data.list9.tile1.tileID = (int) reader.ReadInt();
            data.list9.tile1.variant = (byte)reader.ReadByte();
            data.list9.tile2.tileID = (int) reader.ReadInt();
            data.list9.tile2.variant = (byte)reader.ReadByte();
            data.list9.tile3.tileID = (int) reader.ReadInt();
            data.list9.tile3.variant = (byte)reader.ReadByte();
            data.list9.tile4.tileID = (int) reader.ReadInt();
            data.list9.tile4.variant = (byte)reader.ReadByte();
            data.list9.tile5.tileID = (int) reader.ReadInt();
            data.list9.tile5.variant = (byte)reader.ReadByte();
            data.list9.tile6.tileID = (int) reader.ReadInt();
            data.list9.tile6.variant = (byte)reader.ReadByte();
            data.list9.tile7.tileID = (int) reader.ReadInt();
            data.list9.tile7.variant = (byte)reader.ReadByte();
            data.list9.tile8.tileID = (int) reader.ReadInt();
            data.list9.tile8.variant = (byte)reader.ReadByte();
            data.list9.tile9.tileID = (int) reader.ReadInt();
            data.list9.tile9.variant = (byte)reader.ReadByte();
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<Assembly_CSharp_Generated_FixedChunkSerializer, FixedChunk>(ref parameters);
        }

        static readonly PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }

    [System.Runtime.CompilerServices.CompilerGenerated]
    [UpdateInGroup(typeof(RpcCommandRequestSystemGroup))]
    [CreateAfter(typeof(RpcSystem))]
    [BurstCompile]
    internal partial struct Assembly_CSharp_Generated_FixedChunkRpcCommandRequestSystem : ISystem
    {
        RpcCommandRequest<Assembly_CSharp_Generated_FixedChunkSerializer, FixedChunk> m_Request;
        [BurstCompile]
        struct SendRpc : IJobChunk
        {
            public RpcCommandRequest<Assembly_CSharp_Generated_FixedChunkSerializer, FixedChunk>.SendRpcData data;
            public void Execute(in ArchetypeChunk chunk, int unfilteredChunkIndex, bool useEnabledMask, in v128 chunkEnabledMask)
            {
                Assert.IsFalse(useEnabledMask);
                data.Execute(chunk, unfilteredChunkIndex);
            }
        }
        public void OnCreate(ref SystemState state)
        {
            m_Request.OnCreate(ref state);
        }
        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            var sendJob = new SendRpc{data = m_Request.InitJobData(ref state)};
            state.Dependency = sendJob.Schedule(m_Request.Query, state.Dependency);
        }
    }
}
