#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_NewMessageServerRPCCommandSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
using Unity.Burst;
using Unity.Burst.Intrinsics;
using Unity.Assertions;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp_Generated
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    [BurstCompile]
    internal struct Assembly_CSharp_Generated_NewMessageServerRPCSerializer : IComponentData, IRpcCommandSerializer<NewMessageServerRPC>
    {
        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in NewMessageServerRPC data)
        {
            writer.WriteFixedString512(data.message);
            writer.WriteFixedString128(data.sender);
            writer.WriteLong((long) data.messageTime);
            writer.WriteUInt(data.senderIsServer ? 1u : 0);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state, ref NewMessageServerRPC data)
        {
            data.message = reader.ReadFixedString512();
            data.sender = reader.ReadFixedString128();
            data.messageTime = (long) reader.ReadLong();
            data.senderIsServer = (reader.ReadUInt() != 0) ? true : false;
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<Assembly_CSharp_Generated_NewMessageServerRPCSerializer, NewMessageServerRPC>(ref parameters);
        }

        static readonly PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }

    [System.Runtime.CompilerServices.CompilerGenerated]
    [UpdateInGroup(typeof(RpcCommandRequestSystemGroup))]
    [CreateAfter(typeof(RpcSystem))]
    [BurstCompile]
    internal partial struct Assembly_CSharp_Generated_NewMessageServerRPCRpcCommandRequestSystem : ISystem
    {
        RpcCommandRequest<Assembly_CSharp_Generated_NewMessageServerRPCSerializer, NewMessageServerRPC> m_Request;
        [BurstCompile]
        struct SendRpc : IJobChunk
        {
            public RpcCommandRequest<Assembly_CSharp_Generated_NewMessageServerRPCSerializer, NewMessageServerRPC>.SendRpcData data;
            public void Execute(in ArchetypeChunk chunk, int unfilteredChunkIndex, bool useEnabledMask, in v128 chunkEnabledMask)
            {
                Assert.IsFalse(useEnabledMask);
                data.Execute(chunk, unfilteredChunkIndex);
            }
        }
        public void OnCreate(ref SystemState state)
        {
            m_Request.OnCreate(ref state);
        }
        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            var sendJob = new SendRpc{data = m_Request.InitJobData(ref state)};
            state.Dependency = sendJob.Schedule(m_Request.Query, state.Dependency);
        }
    }
}
