#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_EquipmentEventCounterCommandSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
using Unity.Burst;
using Unity.Burst.Intrinsics;
using System;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;

[assembly: RegisterGenericComponentType(typeof(Unity.NetCode.InputBufferData<EquipmentEventCounter>))]
[assembly: RegisterGenericSystemType(typeof(Unity.NetCode.ApplyCurrentInputBufferElementToInputDataSystem<EquipmentEventCounter, Assembly_CSharp_Generated.Assembly_CSharp_Generated_EquipmentEventCounterEventHelper>))]
[assembly: RegisterGenericSystemType(typeof(Unity.NetCode.ApplyCurrentInputBufferElementToInputDataForGatherSystem<EquipmentEventCounter, Assembly_CSharp_Generated.Assembly_CSharp_Generated_EquipmentEventCounterEventHelper>))]
[assembly: RegisterGenericSystemType(typeof(Unity.NetCode.CopyInputToCommandBufferSystem<EquipmentEventCounter, Assembly_CSharp_Generated.Assembly_CSharp_Generated_EquipmentEventCounterEventHelper>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(Unity.NetCode.ApplyInputDataFromBufferJob<EquipmentEventCounter, Assembly_CSharp_Generated.Assembly_CSharp_Generated_EquipmentEventCounterEventHelper>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(Unity.NetCode.CopyInputToBufferJob<EquipmentEventCounter, Assembly_CSharp_Generated.Assembly_CSharp_Generated_EquipmentEventCounterEventHelper>))]

namespace Assembly_CSharp_Generated
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct Assembly_CSharp_Generated_EquipmentEventCounterEventHelper : IInputEventHelper<EquipmentEventCounter>
    {
        public void DecrementEvents(ref EquipmentEventCounter input, in EquipmentEventCounter prevInput)
        {
        }

        public void IncrementEvents(ref EquipmentEventCounter input, in EquipmentEventCounter lastInput)
        {
        }
    }
}
