#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_PlayerInputCommandSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
using Unity.Burst;
using Unity.Burst.Intrinsics;
using System;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;

[assembly: RegisterGenericComponentType(typeof(Unity.NetCode.InputBufferData<PlayerInput>))]
[assembly: RegisterGenericSystemType(typeof(Unity.NetCode.ApplyCurrentInputBufferElementToInputDataSystem<PlayerInput, Assembly_CSharp_Generated.Assembly_CSharp_Generated_PlayerInputEventHelper>))]
[assembly: RegisterGenericSystemType(typeof(Unity.NetCode.ApplyCurrentInputBufferElementToInputDataForGatherSystem<PlayerInput, Assembly_CSharp_Generated.Assembly_CSharp_Generated_PlayerInputEventHelper>))]
[assembly: RegisterGenericSystemType(typeof(Unity.NetCode.CopyInputToCommandBufferSystem<PlayerInput, Assembly_CSharp_Generated.Assembly_CSharp_Generated_PlayerInputEventHelper>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(Unity.NetCode.ApplyInputDataFromBufferJob<PlayerInput, Assembly_CSharp_Generated.Assembly_CSharp_Generated_PlayerInputEventHelper>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(Unity.NetCode.CopyInputToBufferJob<PlayerInput, Assembly_CSharp_Generated.Assembly_CSharp_Generated_PlayerInputEventHelper>))]

namespace Assembly_CSharp_Generated
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct Assembly_CSharp_Generated_PlayerInputEventHelper : IInputEventHelper<PlayerInput>
    {
        public void DecrementEvents(ref PlayerInput input, in PlayerInput prevInput)
        {
            input.rightButton.Count -= prevInput.rightButton.Count;
            input.leftButton.Count -= prevInput.leftButton.Count;
        }

        public void IncrementEvents(ref PlayerInput input, in PlayerInput lastInput)
        {
            input.rightButton.Count += lastInput.rightButton.Count;
            input.leftButton.Count += lastInput.leftButton.Count;
        }
    }
}
