#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_ChunkEventCounterCommandSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
using Unity.Burst;
using Unity.Burst.Intrinsics;
using System;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;

[assembly: RegisterGenericComponentType(typeof(Unity.NetCode.InputBufferData<ChunkEventCounter>))]
[assembly: RegisterGenericSystemType(typeof(Unity.NetCode.ApplyCurrentInputBufferElementToInputDataSystem<ChunkEventCounter, Assembly_CSharp_Generated.Assembly_CSharp_Generated_ChunkEventCounterEventHelper>))]
[assembly: RegisterGenericSystemType(typeof(Unity.NetCode.ApplyCurrentInputBufferElementToInputDataForGatherSystem<ChunkEventCounter, Assembly_CSharp_Generated.Assembly_CSharp_Generated_ChunkEventCounterEventHelper>))]
[assembly: RegisterGenericSystemType(typeof(Unity.NetCode.CopyInputToCommandBufferSystem<ChunkEventCounter, Assembly_CSharp_Generated.Assembly_CSharp_Generated_ChunkEventCounterEventHelper>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(Unity.NetCode.ApplyInputDataFromBufferJob<ChunkEventCounter, Assembly_CSharp_Generated.Assembly_CSharp_Generated_ChunkEventCounterEventHelper>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(Unity.NetCode.CopyInputToBufferJob<ChunkEventCounter, Assembly_CSharp_Generated.Assembly_CSharp_Generated_ChunkEventCounterEventHelper>))]

namespace Assembly_CSharp_Generated
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct Assembly_CSharp_Generated_ChunkEventCounterEventHelper : IInputEventHelper<ChunkEventCounter>
    {
        public void DecrementEvents(ref ChunkEventCounter input, in ChunkEventCounter prevInput)
        {
        }

        public void IncrementEvents(ref ChunkEventCounter input, in ChunkEventCounter lastInput)
        {
        }
    }
}
