#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_Fixed100BytesCommandSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
using Unity.Burst;
using Unity.Burst.Intrinsics;
using Unity.Assertions;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp_Generated
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    [BurstCompile]
    internal struct Assembly_CSharp_Generated_Fixed100BytesSerializer : IComponentData, IRpcCommandSerializer<Fixed100Bytes>
    {
        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in Fixed100Bytes data)
        {
            writer.WriteLong((long) data.bytes0.bytes0);
            writer.WriteLong((long) data.bytes0.bytes1);
            writer.WriteLong((long) data.bytes0.bytes2);
            writer.WriteLong((long) data.bytes0.bytes3);
            writer.WriteLong((long) data.bytes0.bytes4);
            writer.WriteLong((long) data.bytes0.bytes5);
            writer.WriteLong((long) data.bytes0.bytes6);
            writer.WriteLong((long) data.bytes0.bytes7);
            writer.WriteLong((long) data.bytes0.bytes8);
            writer.WriteLong((long) data.bytes0.bytes9);
            writer.WriteLong((long) data.bytes1.bytes0);
            writer.WriteLong((long) data.bytes1.bytes1);
            writer.WriteLong((long) data.bytes1.bytes2);
            writer.WriteLong((long) data.bytes1.bytes3);
            writer.WriteLong((long) data.bytes1.bytes4);
            writer.WriteLong((long) data.bytes1.bytes5);
            writer.WriteLong((long) data.bytes1.bytes6);
            writer.WriteLong((long) data.bytes1.bytes7);
            writer.WriteLong((long) data.bytes1.bytes8);
            writer.WriteLong((long) data.bytes1.bytes9);
            writer.WriteLong((long) data.bytes2.bytes0);
            writer.WriteLong((long) data.bytes2.bytes1);
            writer.WriteLong((long) data.bytes2.bytes2);
            writer.WriteLong((long) data.bytes2.bytes3);
            writer.WriteLong((long) data.bytes2.bytes4);
            writer.WriteLong((long) data.bytes2.bytes5);
            writer.WriteLong((long) data.bytes2.bytes6);
            writer.WriteLong((long) data.bytes2.bytes7);
            writer.WriteLong((long) data.bytes2.bytes8);
            writer.WriteLong((long) data.bytes2.bytes9);
            writer.WriteLong((long) data.bytes3.bytes0);
            writer.WriteLong((long) data.bytes3.bytes1);
            writer.WriteLong((long) data.bytes3.bytes2);
            writer.WriteLong((long) data.bytes3.bytes3);
            writer.WriteLong((long) data.bytes3.bytes4);
            writer.WriteLong((long) data.bytes3.bytes5);
            writer.WriteLong((long) data.bytes3.bytes6);
            writer.WriteLong((long) data.bytes3.bytes7);
            writer.WriteLong((long) data.bytes3.bytes8);
            writer.WriteLong((long) data.bytes3.bytes9);
            writer.WriteLong((long) data.bytes4.bytes0);
            writer.WriteLong((long) data.bytes4.bytes1);
            writer.WriteLong((long) data.bytes4.bytes2);
            writer.WriteLong((long) data.bytes4.bytes3);
            writer.WriteLong((long) data.bytes4.bytes4);
            writer.WriteLong((long) data.bytes4.bytes5);
            writer.WriteLong((long) data.bytes4.bytes6);
            writer.WriteLong((long) data.bytes4.bytes7);
            writer.WriteLong((long) data.bytes4.bytes8);
            writer.WriteLong((long) data.bytes4.bytes9);
            writer.WriteLong((long) data.bytes5.bytes0);
            writer.WriteLong((long) data.bytes5.bytes1);
            writer.WriteLong((long) data.bytes5.bytes2);
            writer.WriteLong((long) data.bytes5.bytes3);
            writer.WriteLong((long) data.bytes5.bytes4);
            writer.WriteLong((long) data.bytes5.bytes5);
            writer.WriteLong((long) data.bytes5.bytes6);
            writer.WriteLong((long) data.bytes5.bytes7);
            writer.WriteLong((long) data.bytes5.bytes8);
            writer.WriteLong((long) data.bytes5.bytes9);
            writer.WriteLong((long) data.bytes6.bytes0);
            writer.WriteLong((long) data.bytes6.bytes1);
            writer.WriteLong((long) data.bytes6.bytes2);
            writer.WriteLong((long) data.bytes6.bytes3);
            writer.WriteLong((long) data.bytes6.bytes4);
            writer.WriteLong((long) data.bytes6.bytes5);
            writer.WriteLong((long) data.bytes6.bytes6);
            writer.WriteLong((long) data.bytes6.bytes7);
            writer.WriteLong((long) data.bytes6.bytes8);
            writer.WriteLong((long) data.bytes6.bytes9);
            writer.WriteLong((long) data.bytes7.bytes0);
            writer.WriteLong((long) data.bytes7.bytes1);
            writer.WriteLong((long) data.bytes7.bytes2);
            writer.WriteLong((long) data.bytes7.bytes3);
            writer.WriteLong((long) data.bytes7.bytes4);
            writer.WriteLong((long) data.bytes7.bytes5);
            writer.WriteLong((long) data.bytes7.bytes6);
            writer.WriteLong((long) data.bytes7.bytes7);
            writer.WriteLong((long) data.bytes7.bytes8);
            writer.WriteLong((long) data.bytes7.bytes9);
            writer.WriteLong((long) data.bytes8.bytes0);
            writer.WriteLong((long) data.bytes8.bytes1);
            writer.WriteLong((long) data.bytes8.bytes2);
            writer.WriteLong((long) data.bytes8.bytes3);
            writer.WriteLong((long) data.bytes8.bytes4);
            writer.WriteLong((long) data.bytes8.bytes5);
            writer.WriteLong((long) data.bytes8.bytes6);
            writer.WriteLong((long) data.bytes8.bytes7);
            writer.WriteLong((long) data.bytes8.bytes8);
            writer.WriteLong((long) data.bytes8.bytes9);
            writer.WriteLong((long) data.bytes9.bytes0);
            writer.WriteLong((long) data.bytes9.bytes1);
            writer.WriteLong((long) data.bytes9.bytes2);
            writer.WriteLong((long) data.bytes9.bytes3);
            writer.WriteLong((long) data.bytes9.bytes4);
            writer.WriteLong((long) data.bytes9.bytes5);
            writer.WriteLong((long) data.bytes9.bytes6);
            writer.WriteLong((long) data.bytes9.bytes7);
            writer.WriteLong((long) data.bytes9.bytes8);
            writer.WriteLong((long) data.bytes9.bytes9);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state, ref Fixed100Bytes data)
        {
            data.bytes0.bytes0 = (long) reader.ReadLong();
            data.bytes0.bytes1 = (long) reader.ReadLong();
            data.bytes0.bytes2 = (long) reader.ReadLong();
            data.bytes0.bytes3 = (long) reader.ReadLong();
            data.bytes0.bytes4 = (long) reader.ReadLong();
            data.bytes0.bytes5 = (long) reader.ReadLong();
            data.bytes0.bytes6 = (long) reader.ReadLong();
            data.bytes0.bytes7 = (long) reader.ReadLong();
            data.bytes0.bytes8 = (long) reader.ReadLong();
            data.bytes0.bytes9 = (long) reader.ReadLong();
            data.bytes1.bytes0 = (long) reader.ReadLong();
            data.bytes1.bytes1 = (long) reader.ReadLong();
            data.bytes1.bytes2 = (long) reader.ReadLong();
            data.bytes1.bytes3 = (long) reader.ReadLong();
            data.bytes1.bytes4 = (long) reader.ReadLong();
            data.bytes1.bytes5 = (long) reader.ReadLong();
            data.bytes1.bytes6 = (long) reader.ReadLong();
            data.bytes1.bytes7 = (long) reader.ReadLong();
            data.bytes1.bytes8 = (long) reader.ReadLong();
            data.bytes1.bytes9 = (long) reader.ReadLong();
            data.bytes2.bytes0 = (long) reader.ReadLong();
            data.bytes2.bytes1 = (long) reader.ReadLong();
            data.bytes2.bytes2 = (long) reader.ReadLong();
            data.bytes2.bytes3 = (long) reader.ReadLong();
            data.bytes2.bytes4 = (long) reader.ReadLong();
            data.bytes2.bytes5 = (long) reader.ReadLong();
            data.bytes2.bytes6 = (long) reader.ReadLong();
            data.bytes2.bytes7 = (long) reader.ReadLong();
            data.bytes2.bytes8 = (long) reader.ReadLong();
            data.bytes2.bytes9 = (long) reader.ReadLong();
            data.bytes3.bytes0 = (long) reader.ReadLong();
            data.bytes3.bytes1 = (long) reader.ReadLong();
            data.bytes3.bytes2 = (long) reader.ReadLong();
            data.bytes3.bytes3 = (long) reader.ReadLong();
            data.bytes3.bytes4 = (long) reader.ReadLong();
            data.bytes3.bytes5 = (long) reader.ReadLong();
            data.bytes3.bytes6 = (long) reader.ReadLong();
            data.bytes3.bytes7 = (long) reader.ReadLong();
            data.bytes3.bytes8 = (long) reader.ReadLong();
            data.bytes3.bytes9 = (long) reader.ReadLong();
            data.bytes4.bytes0 = (long) reader.ReadLong();
            data.bytes4.bytes1 = (long) reader.ReadLong();
            data.bytes4.bytes2 = (long) reader.ReadLong();
            data.bytes4.bytes3 = (long) reader.ReadLong();
            data.bytes4.bytes4 = (long) reader.ReadLong();
            data.bytes4.bytes5 = (long) reader.ReadLong();
            data.bytes4.bytes6 = (long) reader.ReadLong();
            data.bytes4.bytes7 = (long) reader.ReadLong();
            data.bytes4.bytes8 = (long) reader.ReadLong();
            data.bytes4.bytes9 = (long) reader.ReadLong();
            data.bytes5.bytes0 = (long) reader.ReadLong();
            data.bytes5.bytes1 = (long) reader.ReadLong();
            data.bytes5.bytes2 = (long) reader.ReadLong();
            data.bytes5.bytes3 = (long) reader.ReadLong();
            data.bytes5.bytes4 = (long) reader.ReadLong();
            data.bytes5.bytes5 = (long) reader.ReadLong();
            data.bytes5.bytes6 = (long) reader.ReadLong();
            data.bytes5.bytes7 = (long) reader.ReadLong();
            data.bytes5.bytes8 = (long) reader.ReadLong();
            data.bytes5.bytes9 = (long) reader.ReadLong();
            data.bytes6.bytes0 = (long) reader.ReadLong();
            data.bytes6.bytes1 = (long) reader.ReadLong();
            data.bytes6.bytes2 = (long) reader.ReadLong();
            data.bytes6.bytes3 = (long) reader.ReadLong();
            data.bytes6.bytes4 = (long) reader.ReadLong();
            data.bytes6.bytes5 = (long) reader.ReadLong();
            data.bytes6.bytes6 = (long) reader.ReadLong();
            data.bytes6.bytes7 = (long) reader.ReadLong();
            data.bytes6.bytes8 = (long) reader.ReadLong();
            data.bytes6.bytes9 = (long) reader.ReadLong();
            data.bytes7.bytes0 = (long) reader.ReadLong();
            data.bytes7.bytes1 = (long) reader.ReadLong();
            data.bytes7.bytes2 = (long) reader.ReadLong();
            data.bytes7.bytes3 = (long) reader.ReadLong();
            data.bytes7.bytes4 = (long) reader.ReadLong();
            data.bytes7.bytes5 = (long) reader.ReadLong();
            data.bytes7.bytes6 = (long) reader.ReadLong();
            data.bytes7.bytes7 = (long) reader.ReadLong();
            data.bytes7.bytes8 = (long) reader.ReadLong();
            data.bytes7.bytes9 = (long) reader.ReadLong();
            data.bytes8.bytes0 = (long) reader.ReadLong();
            data.bytes8.bytes1 = (long) reader.ReadLong();
            data.bytes8.bytes2 = (long) reader.ReadLong();
            data.bytes8.bytes3 = (long) reader.ReadLong();
            data.bytes8.bytes4 = (long) reader.ReadLong();
            data.bytes8.bytes5 = (long) reader.ReadLong();
            data.bytes8.bytes6 = (long) reader.ReadLong();
            data.bytes8.bytes7 = (long) reader.ReadLong();
            data.bytes8.bytes8 = (long) reader.ReadLong();
            data.bytes8.bytes9 = (long) reader.ReadLong();
            data.bytes9.bytes0 = (long) reader.ReadLong();
            data.bytes9.bytes1 = (long) reader.ReadLong();
            data.bytes9.bytes2 = (long) reader.ReadLong();
            data.bytes9.bytes3 = (long) reader.ReadLong();
            data.bytes9.bytes4 = (long) reader.ReadLong();
            data.bytes9.bytes5 = (long) reader.ReadLong();
            data.bytes9.bytes6 = (long) reader.ReadLong();
            data.bytes9.bytes7 = (long) reader.ReadLong();
            data.bytes9.bytes8 = (long) reader.ReadLong();
            data.bytes9.bytes9 = (long) reader.ReadLong();
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<Assembly_CSharp_Generated_Fixed100BytesSerializer, Fixed100Bytes>(ref parameters);
        }

        static readonly PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }

    [System.Runtime.CompilerServices.CompilerGenerated]
    [UpdateInGroup(typeof(RpcCommandRequestSystemGroup))]
    [CreateAfter(typeof(RpcSystem))]
    [BurstCompile]
    internal partial struct Assembly_CSharp_Generated_Fixed100BytesRpcCommandRequestSystem : ISystem
    {
        RpcCommandRequest<Assembly_CSharp_Generated_Fixed100BytesSerializer, Fixed100Bytes> m_Request;
        [BurstCompile]
        struct SendRpc : IJobChunk
        {
            public RpcCommandRequest<Assembly_CSharp_Generated_Fixed100BytesSerializer, Fixed100Bytes>.SendRpcData data;
            public void Execute(in ArchetypeChunk chunk, int unfilteredChunkIndex, bool useEnabledMask, in v128 chunkEnabledMask)
            {
                Assert.IsFalse(useEnabledMask);
                data.Execute(chunk, unfilteredChunkIndex);
            }
        }
        public void OnCreate(ref SystemState state)
        {
            m_Request.OnCreate(ref state);
        }
        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            var sendJob = new SendRpc{data = m_Request.InitJobData(ref state)};
            state.Dependency = sendJob.Schedule(m_Request.Query, state.Dependency);
        }
    }
}
