#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_PlayerSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
#define COMPONENT_HAS_GHOST_FIELDS

using System;
using System.Runtime.CompilerServices;
using System.Diagnostics;
using Unity.Burst;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;

namespace Assembly_CSharp_Generated
{
    /// <summary>
    /// Auto-Generated struct implementing the IGhostSerializer and used to
    /// serialize/deserialize components and buffers.
    /// </summary>
    public partial struct Assembly_CSharp_Generated_PlayerGhostComponentSerializer : IGhostSerializer
    {
        /// <summary>
        /// Internal compoment representation used for serialization/deserialization purpose.
        /// </summary>
        internal struct Snapshot
        {
            public float speed;
            public FixedString128Bytes playerName;
            public float armor;
            public float insulation;
            public float waterResistance;
            public float aesthetic;
            public float wetness;
        }
        /// <summary>The total number of bits used for the change mask.</summary>
        private const int ChangeMaskBits = 7;
        /// <summary>The number of bits used for the change mask.</summary>
        public int ChangeMaskSizeInBits => ChangeMaskBits;
        #if COMPONENT_HAS_GHOST_FIELDS
        /// <summary>Denote if fields are serialized or not.</summary>
        public bool HasGhostFields => true;
        /// <summary>The size in bytes of the Snasphot struct.</summary>
        public int SizeInSnapshot => UnsafeUtility.SizeOf<Snapshot>();
        #else
        /// <summary>Denote if fields are serialized or not.</summary>
        public bool HasGhostFields => false;
        /// <summary>The size in bytes of the Snasphot struct.</summary>
        public int SizeInSnapshot => 0;
        #endif

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.CopyToSnapshotGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void CopyToSnapshotGenerated(in GhostSerializerState serializerState, ref Snapshot snapshot, ref Player component)
        {
                snapshot.speed = component.speed;
                snapshot.playerName = component.playerName;
                snapshot.armor = component.armor;
                snapshot.insulation = component.insulation;
                snapshot.waterResistance = component.waterResistance;
                snapshot.aesthetic = component.aesthetic;
                snapshot.wetness = component.wetness;
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.CopyFromSnapshotGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void CopyFromSnapshotGenerated(in GhostDeserializerState deserializerState, ref Player component,
            float snapshotInterpolationFactor, float snapshotInterpolationFactorRaw, ref Snapshot snapshotBefore, ref Snapshot snapshotAfter)
        {
                component.speed = snapshotBefore.speed;
                component.playerName = snapshotBefore.playerName;
                component.armor = snapshotBefore.armor;
                component.insulation = snapshotBefore.insulation;
                component.waterResistance = snapshotBefore.waterResistance;
                component.aesthetic = snapshotBefore.aesthetic;
                component.wetness = snapshotBefore.wetness;
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.RestoreFromBackupGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void RestoreFromBackupGenerated(ref Player component, ref Player backup)
        {
            component.speed = backup.speed;
            component.playerName = backup.playerName;
            component.armor = backup.armor;
            component.insulation = backup.insulation;
            component.waterResistance = backup.waterResistance;
            component.aesthetic = backup.aesthetic;
            component.wetness = backup.wetness;
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.PredictDeltaGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void PredictDeltaGenerated(ref Snapshot snapshot, ref Snapshot baseline1, ref Snapshot baseline2,
            ref GhostDeltaPredictor predictor)
        {
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.CalculateChangeMaskGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void CalculateChangeMaskGenerated(ref Snapshot snapshot, ref Snapshot baseline,
            [NoAlias]IntPtr changeMaskData, int startOffset)
        {
            uint changeMask = 0;
            changeMask = (snapshot.speed != baseline.speed) ? 1u : 0;
            changeMask |= snapshot.playerName.Equals(baseline.playerName) ? 0 : (1u<<1);
            changeMask |= (snapshot.armor != baseline.armor) ? (1u<<2) : 0;
            changeMask |= (snapshot.insulation != baseline.insulation) ? (1u<<3) : 0;
            changeMask |= (snapshot.waterResistance != baseline.waterResistance) ? (1u<<4) : 0;
            changeMask |= (snapshot.aesthetic != baseline.aesthetic) ? (1u<<5) : 0;
            changeMask |= (snapshot.wetness != baseline.wetness) ? (1u<<6) : 0;
            GhostComponentSerializer.CopyToChangeMask(changeMaskData, changeMask, startOffset + 0, 7);
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.SerializeGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void SerializeGenerated(ref Snapshot snapshot, ref Snapshot baseline,
            [NoAlias]IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedFloatDelta(snapshot.speed, baseline.speed, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedFixedString128Delta(snapshot.playerName, baseline.playerName, compressionModel);
            if ((changeMask & (1 << 2)) != 0)
                writer.WritePackedFloatDelta(snapshot.armor, baseline.armor, compressionModel);
            if ((changeMask & (1 << 3)) != 0)
                writer.WritePackedFloatDelta(snapshot.insulation, baseline.insulation, compressionModel);
            if ((changeMask & (1 << 4)) != 0)
                writer.WritePackedFloatDelta(snapshot.waterResistance, baseline.waterResistance, compressionModel);
            if ((changeMask & (1 << 5)) != 0)
                writer.WritePackedFloatDelta(snapshot.aesthetic, baseline.aesthetic, compressionModel);
            if ((changeMask & (1 << 6)) != 0)
                writer.WritePackedFloatDelta(snapshot.wetness, baseline.wetness, compressionModel);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void SerializeCombinedGenerated(ref Snapshot snapshot, ref Snapshot baseline,
            [NoAlias]IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            uint changeMask = 0;
            changeMask = (snapshot.speed != baseline.speed) ? 1u : 0;
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedFloatDelta(snapshot.speed, baseline.speed, compressionModel);
            changeMask |= snapshot.playerName.Equals(baseline.playerName) ? 0 : (1u<<1);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedFixedString128Delta(snapshot.playerName, baseline.playerName, compressionModel);
            changeMask |= (snapshot.armor != baseline.armor) ? (1u<<2) : 0;
            if ((changeMask & (1 << 2)) != 0)
                writer.WritePackedFloatDelta(snapshot.armor, baseline.armor, compressionModel);
            changeMask |= (snapshot.insulation != baseline.insulation) ? (1u<<3) : 0;
            if ((changeMask & (1 << 3)) != 0)
                writer.WritePackedFloatDelta(snapshot.insulation, baseline.insulation, compressionModel);
            changeMask |= (snapshot.waterResistance != baseline.waterResistance) ? (1u<<4) : 0;
            if ((changeMask & (1 << 4)) != 0)
                writer.WritePackedFloatDelta(snapshot.waterResistance, baseline.waterResistance, compressionModel);
            changeMask |= (snapshot.aesthetic != baseline.aesthetic) ? (1u<<5) : 0;
            if ((changeMask & (1 << 5)) != 0)
                writer.WritePackedFloatDelta(snapshot.aesthetic, baseline.aesthetic, compressionModel);
            changeMask |= (snapshot.wetness != baseline.wetness) ? (1u<<6) : 0;
            if ((changeMask & (1 << 6)) != 0)
                writer.WritePackedFloatDelta(snapshot.wetness, baseline.wetness, compressionModel);
            GhostComponentSerializer.CopyToChangeMask(changeMaskData, changeMask, startOffset + 0, 7);
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.DeserializeGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void DeserializeGenerated(ref DataStreamReader reader,
            in StreamCompressionModel compressionModel,
            IntPtr changeMaskData, int startOffset, ref Snapshot snapshot, ref Snapshot baseline)
        {
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                snapshot.speed = reader.ReadPackedFloatDelta(baseline.speed, compressionModel);
            else
                snapshot.speed = baseline.speed;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.playerName = reader.ReadPackedFixedString128Delta(baseline.playerName, compressionModel);
            else
                snapshot.playerName = baseline.playerName;
            if ((changeMask & (1 << 2)) != 0)
                snapshot.armor = reader.ReadPackedFloatDelta(baseline.armor, compressionModel);
            else
                snapshot.armor = baseline.armor;
            if ((changeMask & (1 << 3)) != 0)
                snapshot.insulation = reader.ReadPackedFloatDelta(baseline.insulation, compressionModel);
            else
                snapshot.insulation = baseline.insulation;
            if ((changeMask & (1 << 4)) != 0)
                snapshot.waterResistance = reader.ReadPackedFloatDelta(baseline.waterResistance, compressionModel);
            else
                snapshot.waterResistance = baseline.waterResistance;
            if ((changeMask & (1 << 5)) != 0)
                snapshot.aesthetic = reader.ReadPackedFloatDelta(baseline.aesthetic, compressionModel);
            else
                snapshot.aesthetic = baseline.aesthetic;
            if ((changeMask & (1 << 6)) != 0)
                snapshot.wetness = reader.ReadPackedFloatDelta(baseline.wetness, compressionModel);
            else
                snapshot.wetness = baseline.wetness;
        }

#if UNITY_EDITOR || NETCODE_DEBUG
        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.ReportPredictionErrorsGenerated"/>
        static void ReportPredictionErrorsGenerated(in Player component, in Player backup, IntPtr errorsList,
            int errorsCount)
        {
            var errors = GhostComponentSerializer.ConvertToUnsafeList(errorsList, errorsCount);
            int errorIndex = 0;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.speed - backup.speed));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.armor - backup.armor));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.insulation - backup.insulation));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.waterResistance - backup.waterResistance));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.aesthetic - backup.aesthetic));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.wetness - backup.wetness));
            ++errorIndex;
        }

        static internal int GetPredictionErrorNamesGenerated(ref FixedString512Bytes names)
        {
            var nameCount = 0;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".speed");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".armor");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".insulation");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".waterResistance");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".aesthetic");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".wetness");
            ++nameCount;
            return nameCount;
        }
#endif

        /// <inheritdoc cref="IGhostSerializer.CopyToSnapshot"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CopyToSnapshot(in GhostSerializerState serializerState, [NoAlias]IntPtr snapshot, [NoAlias][ReadOnly]IntPtr component)
        {
            CopyToSnapshotGenerated(serializerState, ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Player>(component));
        }

        /// <inheritdoc cref="IGhostSerializer.CopyToSnapshot"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CopyFromSnapshot(in GhostDeserializerState serializerState, [NoAlias]IntPtr component,
            float snapshotInterpolationFactor, float snapshotInterpolationFactorRaw, [NoAlias][ReadOnly]IntPtr snapshotBefore,
            [NoAlias][ReadOnly]IntPtr snapshotAfter)
        {
            CopyFromSnapshotGenerated(serializerState,
                ref GhostComponentSerializer.TypeCast<Player>(component),
                snapshotInterpolationFactor,snapshotInterpolationFactorRaw,
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotBefore),
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotAfter));
        }

        /// <inheritdoc cref="IGhostSerializer.CalculateChangeMask"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CalculateChangeMask([NoAlias] [ReadOnly] IntPtr snapshot,
            [NoAlias] [ReadOnly] IntPtr baseline, [NoAlias] IntPtr changeMaskData, int startOffset)
        {
            CalculateChangeMaskGenerated(ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline),
                changeMaskData, startOffset);
        }

        /// <inheritdoc cref="IGhostSerializer.PredictDelta"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void PredictDelta([NoAlias] IntPtr snapshotData,
            [NoAlias] IntPtr baseline1Data, [NoAlias] IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline1 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1Data);
            ref var baseline2 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2Data);
            PredictDeltaGenerated(ref snapshot, ref baseline1, ref baseline2, ref predictor);
        }

        /// <inheritdoc cref="IGhostSerializer.SerializeWithPredictedBaseline"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SerializeWithPredictedBaseline([ReadOnly] [NoAlias] IntPtr snapshot,
            [ReadOnly] [NoAlias] IntPtr baseline0,
            [ReadOnly] [NoAlias] IntPtr baseline1,
            [ReadOnly] [NoAlias] IntPtr baseline2,
            ref GhostDeltaPredictor predictor,
            [NoAlias] [ReadOnly] IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            var baseline = GhostComponentSerializer.TypeCast<Snapshot>(baseline0);
            PredictDeltaGenerated(ref baseline,
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2),
                ref predictor);
            SerializeCombinedGenerated(
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref baseline,
                changeMaskData, startOffset,
                ref writer, compressionModel);
        }

        /// <inheritdoc cref="IGhostSerializer.SerializeCombined"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SerializeCombined([ReadOnly] [NoAlias] IntPtr snapshot,
            [ReadOnly] [NoAlias] IntPtr baseline,
            [NoAlias] [ReadOnly] IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            SerializeCombinedGenerated(
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline),
                changeMaskData, startOffset,
                ref writer, compressionModel);
        }

        /// <inheritdoc cref="IGhostSerializer.Serialize"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Serialize([ReadOnly] [NoAlias] IntPtr snapshot,
            [ReadOnly] [NoAlias] IntPtr baseline,
            [NoAlias] [ReadOnly] IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            SerializeGenerated(
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline),
                changeMaskData, startOffset,
                ref writer, compressionModel);
        }

        /// <inheritdoc cref="IGhostSerializer.Deserialize"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Deserialize(ref DataStreamReader reader, in StreamCompressionModel compressionModel,
            IntPtr changeMask,
            int startOffset, [NoAlias]IntPtr snapshot, [NoAlias][ReadOnly]IntPtr baseline)

        {
            DeserializeGenerated(ref reader, compressionModel, changeMask, startOffset,
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline));
        }

        /// <inheritdoc cref="IGhostSerializer.Deserialize"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void RestoreFromBackup([NoAlias] IntPtr component, [NoAlias] [ReadOnly] IntPtr backup)
        {
            RestoreFromBackupGenerated(
                ref GhostComponentSerializer.TypeCast<Player>(component),
                ref GhostComponentSerializer.TypeCast<Player>(backup));
        }

#if UNITY_EDITOR || NETCODE_DEBUG
        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.ReportPredictionErrorsGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void ReportPredictionErrors([NoAlias][ReadOnly]IntPtr component, [NoAlias][ReadOnly]IntPtr backup, IntPtr errorsList,
            int errorsCount)
        {
            ReportPredictionErrorsGenerated(GhostComponentSerializer.TypeCast<Player>(component),
                GhostComponentSerializer.TypeCast<Player>(backup), errorsList, errorsCount);
        }
#endif
    }

    //Registration
    [BurstCompile]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial struct Assembly_CSharp_Generated_PlayerGhostComponentSerializer : IGhostSerializer
    {
        static internal GhostComponentSerializer.State GetState(ref SystemState state)
        {
            // This needs to be lazy initialized because otherwise there is a depenency on the static initialization order which breaks il2cpp builds, due to TypeManager not being initialized yet.
            // Also, Burst function pointer compilation can take a while.
            if (!s_StateInitialized)
            {
                s_State = new GhostComponentSerializer.State
                {
                    GhostFieldsHash = 1966819302090705106,
                    ComponentType = ComponentType.ReadWrite<Player>(),
                    ComponentSize = UnsafeUtility.SizeOf<Player>(),
#if COMPONENT_HAS_GHOST_FIELDS
                    SnapshotSize = UnsafeUtility.SizeOf<Snapshot>(),
#else
                    SnapshotSize = 0,
#endif
                    ChangeMaskBits = 7,
                    PrefabType = GhostPrefabType.All,
                    SendMask = GhostSendType.AllClients,
                    SendToOwner = SendToOwnerType.All,
                    VariantHash = 4086804167088025962,
                    SerializationStrategyIndex = -1,
                    SerializesEnabledBit = 0,
#if UNITY_EDITOR || NETCODE_DEBUG
                    ProfilerMarker = new Unity.Profiling.ProfilerMarker("Player"),
                    VariantTypeFullNameHash = TypeHash.FNV1A64("Player")
#endif
                };
                // UnsafeUtility.SizeOf<T> reports 1 with zero-sized components.
                if (s_State.ComponentType.IsZeroSized)
                    s_State.ComponentSize = 0;

#if UNITY_EDITOR || NETCODE_DEBUG
                s_State.ProfilerMarker.Begin();
                var innerMarker = new Unity.Profiling.ProfilerMarker("Assembly_CSharp_Generated_Player");
                innerMarker.Begin();
#endif
                s_StateInitialized = SetupFunctionPointers(ref s_State, ref state);
                //TODO: DOTS-7926 we should understand why we have in some cases a StackOverflowException.
                //UNCOMMENT THIS LINE TO DEBUG IF A BIG COMPONENT MAY BE CAUSING A STACK OVERFLOW
                // const int maxSizeToAvoidStackOverflow = 4_500;
                // if (s_State.ComponentSize > maxSizeToAvoidStackOverflow)
                // {
                //     UnityEngine.Debug.LogWarning($"The type '{s_State.ComponentType}' is very large ({s_State.ComponentSize} bytes)! There is a risk of StackOverflowExceptions in the Serializers at roughly {maxSizeToAvoidStackOverflow} bytes! Remove large fields.");
                // }
#if UNITY_EDITOR || NETCODE_DEBUG
                s_State.NumPredictionErrors = GetPredictionErrorNamesGenerated(ref s_State.PredictionErrorNames);
#endif

#if UNITY_EDITOR || NETCODE_DEBUG
                innerMarker.End();
                s_State.ProfilerMarker.End();
#endif
            }
            return s_State;
        }

        private static bool s_StateInitialized;
        private static GhostComponentSerializer.State s_State;

        private static bool SetupFunctionPointers(ref GhostComponentSerializer.State state,
            ref SystemState systemState)
        {
            // Optimization: Creating burst functions is expensive.
            // We don't need to do it in literally any other words as they're never called.
            if ((systemState.WorldUnmanaged.Flags & WorldFlags.GameServer) != WorldFlags.GameServer
                && (systemState.WorldUnmanaged.Flags & WorldFlags.GameClient) != WorldFlags.GameClient
                && (systemState.WorldUnmanaged.Flags & WorldFlags.GameThinClient) != WorldFlags.GameThinClient)
                return false;

#if !GHOST_COMPONENT_IS_BUFFER
            state.PostSerialize = new PortableFunctionPointer<GhostComponentSerializer.PostSerializeDelegate>(
                AOT_PostSerialize);
            state.Serialize = new PortableFunctionPointer<GhostComponentSerializer.SerializeDelegate>(
                AOT_Serialize);
#else
            state.PostSerializeBuffer = new PortableFunctionPointer<GhostComponentSerializer.PostSerializeBufferDelegate>(
                AOT_PostSerializeBuffer);
            state.SerializeBuffer = new PortableFunctionPointer<GhostComponentSerializer.SerializeBufferDelegate>(
                AOT_SerializeBuffer);
#endif
            state.CopyFromSnapshot = new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(
                AOT_CopyFromSnapshot);
            state.CopyToSnapshot = new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(
                AOT_CopyToSnapshot);
            state.RestoreFromBackup = new PortableFunctionPointer<GhostComponentSerializer.RestoreFromBackupDelegate>(
                AOT_RestoreFromBackup);
            state.PredictDelta = new PortableFunctionPointer<GhostComponentSerializer.PredictDeltaDelegate>(
                AOT_PredictDelta);
            state.Deserialize = new PortableFunctionPointer<GhostComponentSerializer.DeserializeDelegate>(
                AOT_Deserialize);
#if UNITY_EDITOR || NETCODE_DEBUG
            state.ReportPredictionErrors = new PortableFunctionPointer<GhostComponentSerializer.ReportPredictionErrorsDelegate>(
                AOT_ReportPredictionErrors);
#endif
            return true;
        }

#if !GHOST_COMPONENT_IS_BUFFER
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.PostSerializeDelegate))]
        private static void AOT_PostSerialize(IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            int maskOffsetInBits,
            int count, IntPtr baselines, ref DataStreamWriter writer,
            ref StreamCompressionModel compressionModel,
            IntPtr entityStartBit)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerGhostComponentSerializer);
            Unity.NetCode.ComponentSerializationHelper<
                    Player,
                    Snapshot,
                    Assembly_CSharp_Generated_PlayerGhostComponentSerializer
            >.PostSerializeComponents(serializer,
                snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, count, baselines,
                ref writer, ref compressionModel, entityStartBit);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void AOT_Serialize([NoAlias]IntPtr stateData,
            IntPtr snapshotData, int snapshotOffset, int snapshotStride, int maskOffsetInBits,
            IntPtr componentData, int count, IntPtr baselines,
            ref DataStreamWriter writer, ref StreamCompressionModel compressionModel, IntPtr entityStartBit)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerGhostComponentSerializer);
            Unity.NetCode.ComponentSerializationHelper<
                    Player,
                    Snapshot,
                    Assembly_CSharp_Generated_PlayerGhostComponentSerializer
            >.SerializeComponents(serializer, stateData, snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, componentData, count, baselines, ref writer, compressionModel, entityStartBit);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
#else
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.PostSerializeDelegate))]
        private static void AOT_PostSerializeBuffer(IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            int maskOffsetInBits, int changeMaskBits, int count, IntPtr baselines,
            ref DataStreamWriter writer, ref StreamCompressionModel compressionModel,
            IntPtr entityStartBit, IntPtr snapshotDynamicDataPtr, IntPtr dynamicSizePerEntity, int dynamicSnapshotMaxOffset)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerGhostComponentSerializer);
            Unity.NetCode.BufferSerializationHelper<
                Player,
                Snapshot,
                Assembly_CSharp_Generated_PlayerGhostComponentSerializer
            >.PostSerializeBuffers(snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, changeMaskBits, count, baselines,
                ref writer, compressionModel, entityStartBit, snapshotDynamicDataPtr, dynamicSizePerEntity, dynamicSnapshotMaxOffset,
                serializer);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void AOT_SerializeBuffer(IntPtr stateData,
            IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            int maskOffsetInBits, int changeMaskBits,
            IntPtr componentData, IntPtr componentDataLen, int count, [NoAlias]IntPtr baselines,
            ref DataStreamWriter writer, ref StreamCompressionModel compressionModel,
            IntPtr entityStartBit, IntPtr snapshotDynamicDataPtr, ref int dynamicSnapshotDataOffset,
            IntPtr dynamicSizePerEntity, int dynamicSnapshotMaxOffset)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerGhostComponentSerializer);
            Unity.NetCode.BufferSerializationHelper<
                Player,
                Snapshot,
                Assembly_CSharp_Generated_PlayerGhostComponentSerializer
            >.SerializeBuffers(stateData, snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, changeMaskBits,
                componentData, componentDataLen, count, baselines, ref writer, compressionModel, entityStartBit, snapshotDynamicDataPtr,
                ref dynamicSnapshotDataOffset, dynamicSizePerEntity, dynamicSnapshotMaxOffset, serializer);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
#endif
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void AOT_CopyToSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            IntPtr componentData, int componentStride, int count)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerGhostComponentSerializer);
#if !GHOST_COMPONENT_IS_BUFFER
            Unity.NetCode.ComponentSerializationHelper<
                    Player,
                    Snapshot,
                    Assembly_CSharp_Generated_PlayerGhostComponentSerializer
            >.CopyComponentsToSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#else
            Unity.NetCode.BufferSerializationHelper<
                Player,
                Snapshot,
                Assembly_CSharp_Generated_PlayerGhostComponentSerializer
            >.CopyBuffersToSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#endif
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void AOT_CopyFromSnapshot(IntPtr stateData, IntPtr snapshotData,
            int snapshotOffset, int snapshotStride,
            IntPtr componentData, int componentStride, int count)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerGhostComponentSerializer);
#if !GHOST_COMPONENT_IS_BUFFER
            Unity.NetCode.ComponentSerializationHelper<
                Player,
                Snapshot,
                Assembly_CSharp_Generated_PlayerGhostComponentSerializer
            >.CopyComponentsFromSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#else
            Unity.NetCode.BufferSerializationHelper<
                Player,
                Snapshot,
                Assembly_CSharp_Generated_PlayerGhostComponentSerializer
            >.CopyBuffersFromSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#endif
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.RestoreFromBackupDelegate))]
        private static void AOT_RestoreFromBackup(IntPtr componentData, IntPtr backupData)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerGhostComponentSerializer);
            serializer.RestoreFromBackup(componentData, backupData);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.PredictDeltaDelegate))]
        private static void AOT_PredictDelta(IntPtr snapshotData,
            IntPtr baseline1Data, IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerGhostComponentSerializer);
            serializer.PredictDelta(snapshotData, baseline1Data, baseline2Data, ref predictor);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.DeserializeDelegate))]
        private static void AOT_Deserialize(IntPtr snapshotData, IntPtr baselineData,
            ref DataStreamReader reader, ref StreamCompressionModel compressionModel,
            IntPtr changeMaskData, int startOffset)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerGhostComponentSerializer);
            serializer.Deserialize(ref reader, compressionModel, changeMaskData, startOffset, snapshotData, baselineData);
#endif
        }
#if UNITY_EDITOR || NETCODE_DEBUG
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.ReportPredictionErrorsDelegate))]
        private static void AOT_ReportPredictionErrors(IntPtr componentData, IntPtr backupData,
            IntPtr errorsList, int errorsCount)
        {
            var serializer = default(Assembly_CSharp_Generated_PlayerGhostComponentSerializer);
            serializer.ReportPredictionErrors(componentData, backupData, errorsList, errorsCount);
        }
#endif
    }
}
