#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_GoInGameRequestRPCCommandSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
using Unity.Burst;
using Unity.Burst.Intrinsics;
using Unity.Assertions;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp_Generated
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    [BurstCompile]
    internal struct Assembly_CSharp_Generated_GoInGameRequestRPCSerializer : IComponentData, IRpcCommandSerializer<GoInGameRequestRPC>
    {
        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in GoInGameRequestRPC data)
        {
            writer.WriteFixedString128(data.playerName);
            writer.WriteInt((int) data.characterLook.hairIndex);
            writer.WriteInt((int) data.characterLook.beardndex);
            writer.WriteInt((int) data.characterLook.faceDetailsIndex);
            writer.WriteFloat(data.characterLook.skinColor.x);
            writer.WriteFloat(data.characterLook.skinColor.y);
            writer.WriteFloat(data.characterLook.skinColor.z);
            writer.WriteFloat(data.characterLook.underwearColor.x);
            writer.WriteFloat(data.characterLook.underwearColor.y);
            writer.WriteFloat(data.characterLook.underwearColor.z);
            writer.WriteFloat(data.characterLook.hairColor.x);
            writer.WriteFloat(data.characterLook.hairColor.y);
            writer.WriteFloat(data.characterLook.hairColor.z);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state, ref GoInGameRequestRPC data)
        {
            data.playerName = reader.ReadFixedString128();
            data.characterLook.hairIndex = (int) reader.ReadInt();
            data.characterLook.beardndex = (int) reader.ReadInt();
            data.characterLook.faceDetailsIndex = (int) reader.ReadInt();
            data.characterLook.skinColor.x = reader.ReadFloat();
            data.characterLook.skinColor.y = reader.ReadFloat();
            data.characterLook.skinColor.z = reader.ReadFloat();
            data.characterLook.underwearColor.x = reader.ReadFloat();
            data.characterLook.underwearColor.y = reader.ReadFloat();
            data.characterLook.underwearColor.z = reader.ReadFloat();
            data.characterLook.hairColor.x = reader.ReadFloat();
            data.characterLook.hairColor.y = reader.ReadFloat();
            data.characterLook.hairColor.z = reader.ReadFloat();
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<Assembly_CSharp_Generated_GoInGameRequestRPCSerializer, GoInGameRequestRPC>(ref parameters);
        }

        static readonly PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }

    [System.Runtime.CompilerServices.CompilerGenerated]
    [UpdateInGroup(typeof(RpcCommandRequestSystemGroup))]
    [CreateAfter(typeof(RpcSystem))]
    [BurstCompile]
    internal partial struct Assembly_CSharp_Generated_GoInGameRequestRPCRpcCommandRequestSystem : ISystem
    {
        RpcCommandRequest<Assembly_CSharp_Generated_GoInGameRequestRPCSerializer, GoInGameRequestRPC> m_Request;
        [BurstCompile]
        struct SendRpc : IJobChunk
        {
            public RpcCommandRequest<Assembly_CSharp_Generated_GoInGameRequestRPCSerializer, GoInGameRequestRPC>.SendRpcData data;
            public void Execute(in ArchetypeChunk chunk, int unfilteredChunkIndex, bool useEnabledMask, in v128 chunkEnabledMask)
            {
                Assert.IsFalse(useEnabledMask);
                data.Execute(chunk, unfilteredChunkIndex);
            }
        }
        public void OnCreate(ref SystemState state)
        {
            m_Request.OnCreate(ref state);
        }
        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            var sendJob = new SendRpc{data = m_Request.InitJobData(ref state)};
            state.Dependency = sendJob.Schedule(m_Request.Query, state.Dependency);
        }
    }
}
