#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_EquipmentEventCounterEquipmentEventCounterInputBufferDataCommandSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
using Unity.Burst;
using Unity.Burst.Intrinsics;
using Unity.Collections.LowLevel.Unsafe;
using System.Runtime.CompilerServices;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp_Generated
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataSerializer : ICommandDataSerializer<Unity.NetCode.InputBufferData<EquipmentEventCounter>>
    {
        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in Unity.NetCode.InputBufferData<EquipmentEventCounter> data)
        {
            writer.WriteUInt((uint)data.InternalInput.index);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state, ref Unity.NetCode.InputBufferData<EquipmentEventCounter> data)
        {
            data.InternalInput.index = (uint) reader.ReadUInt();
        }

        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in Unity.NetCode.InputBufferData<EquipmentEventCounter> data, in Unity.NetCode.InputBufferData<EquipmentEventCounter> baseline, StreamCompressionModel compressionModel)
        {
            writer.WritePackedUIntDelta((uint)data.InternalInput.index, (uint)baseline.InternalInput.index, compressionModel);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state, ref Unity.NetCode.InputBufferData<EquipmentEventCounter> data, in Unity.NetCode.InputBufferData<EquipmentEventCounter> baseline, StreamCompressionModel compressionModel)
        {
            data.InternalInput.index = (uint) reader.ReadPackedUIntDelta((uint)baseline.InternalInput.index, compressionModel);
        }

        public uint CalculateChangeMask(in Unity.NetCode.InputBufferData<EquipmentEventCounter> snapshot, in Unity.NetCode.InputBufferData<EquipmentEventCounter> baseline)
        {
            uint changeMask = 0;
            changeMask |= (snapshot.InternalInput.index != baseline.InternalInput.index) ? (1u<<0) : 0;
            return changeMask;
        }

        public FixedString64Bytes ToFixedString() => "EquipmentEventCounter";
    }

    [System.Runtime.CompilerServices.CompilerGenerated]
    [UpdateInGroup(typeof(CommandSendSystemGroup))]
    [BurstCompile]
    internal partial struct Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataSendCommandSystem : ISystem
    {
        CommandSendSystem<Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataSerializer, Unity.NetCode.InputBufferData<EquipmentEventCounter>> m_CommandSend;
        [BurstCompile]
        struct SendJob : IJobChunk
        {
            public CommandSendSystem<Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataSerializer, Unity.NetCode.InputBufferData<EquipmentEventCounter>>.SendJobData data;
            public void Execute(in ArchetypeChunk chunk, int unfilteredChunkIndex, bool useEnabledMask, in v128 chunkEnabledMask)
            {
                data.Execute(chunk, unfilteredChunkIndex);
            }
        }
        [BurstCompile]
        public void OnCreate(ref SystemState state)
        {
            m_CommandSend.OnCreate(ref state);
        }
        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            if (!m_CommandSend.ShouldRunCommandJob(ref state))
                return;
            var sendJob = new SendJob{data = m_CommandSend.InitJobData(ref state)};
            state.Dependency = sendJob.Schedule(m_CommandSend.Query, state.Dependency);
        }
    }

    [System.Runtime.CompilerServices.CompilerGenerated]
    [UpdateInGroup(typeof(CommandReceiveSystemGroup))]
    [BurstCompile]
    internal partial struct Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataReceiveCommandSystem : ISystem
    {
        CommandReceiveSystem<Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataSerializer, Unity.NetCode.InputBufferData<EquipmentEventCounter>> m_CommandRecv;
        [BurstCompile]
        struct ReceiveJob : IJobChunk
        {
            public CommandReceiveSystem<Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataSerializer, Unity.NetCode.InputBufferData<EquipmentEventCounter>>.ReceiveJobData data;
            public void Execute(in ArchetypeChunk chunk, int unfilteredChunkIndex, bool useEnabledMask, in v128 chunkEnabledMask)
            {
                data.Execute(chunk, unfilteredChunkIndex);
            }
        }
        [BurstCompile]
        public void OnCreate(ref SystemState state)
        {
            m_CommandRecv.OnCreate(ref state);
        }
        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            var recvJob = new ReceiveJob{data = m_CommandRecv.InitJobData(ref state)};
            state.Dependency = recvJob.Schedule(m_CommandRecv.Query, state.Dependency);
        }
    }

    [UpdateInGroup(typeof(CompareCommandSystemGroup))]
    [BurstCompile]
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal partial struct Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataCompareCommandSystem : ISystem
    {
        [BurstCompile]
        struct CompareJob : IJobChunk
        {
            public NativeParallelHashMap<NetworkTick,NetworkTick>.ParallelWriter map;
            [ReadOnly] public BufferTypeHandle<Unity.NetCode.InputBufferData<EquipmentEventCounter>> inputTypeHandle;

            public void Execute(in ArchetypeChunk chunk, int unfilteredChunkIndex, bool useEnabledMask, in v128 chunkEnabledMask)
            {
                var inputBufferAccessor = chunk.GetBufferAccessor(ref inputTypeHandle);
                for (int entIdx = 0; entIdx < chunk.Count; ++entIdx)
                {
                    var inputBuffer = inputBufferAccessor[entIdx];
                    var length = inputBuffer.Length;
                    var serializer = new Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataSerializer();
                    //The buffer can be in two state:
                    //1,2,3,4,5,6... 64 (all ordered)
                    //64+1,64+2,64+3,64+4,64+5,6,8,12,10,...64 // split state.
                    //This is also a search done on the client side. That store the input constantly in increasing bucket order.
                    //That imply it is more logic to start the comparison from the "oldest" input and going forward.
                    //Or start from the newest and going backward. We are using the latter.
                    for (int i = 0; i < length; ++i)
                    {
                        ref readonly var curInput = ref inputBuffer.GetInputAtIndex(i);
                        var curTick = curInput.Tick;
                        //We can also stop to the first invalid tick. Because tick are invalid only if the buffer is not full yet.
                        if (!curTick.IsValid)
                            break;
                        var prevTick = curInput.Tick;
                        prevTick.Decrement();
                        //There is not need to search. We know that this is going to be the previous element in the buffer.
                        var beforeIdx = (i - 1 + length) % length;
                        //We can stop as soon as we find the first element that is less than or equal the tick
                        //or that is invalid
                        ref readonly var prevInput = ref inputBuffer.GetInputAtIndex(beforeIdx);
                        //This check requires some explanation. We need to determine if the previous slot is the head of the buffer.
                        //Two cases:
                        //1) prevInput.Tick <= prevTick (considering overlap)
                        //2) prevInput.Tick > prevTick (considering overlap)
                        //if the prevInput is the "head" of the input buffer there cannot be input with a tick less thab prevTick and
                        //we can stop the run.
                        //if the prevInput is <= prevTick we need to check if they are identical.
                        if (!prevInput.Tick.IsValid || prevInput.Tick.IsNewerThan(prevTick) || serializer.CalculateChangeMask(in curInput, in prevInput) != 0)
                            map.TryAdd(curTick, curTick);
                    }
                }
            }
        }
        private EntityQuery m_Query;
        private EntityQuery m_TickMapQuery;
        private BufferTypeHandle<Unity.NetCode.InputBufferData<EquipmentEventCounter>> m_Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataHandle;
        [BurstCompile]
        public void OnCreate(ref SystemState state)
        {
            var builder = new EntityQueryBuilder(Allocator.Temp)
                .WithAllRW<Unity.NetCode.InputBufferData<EquipmentEventCounter>>();
            m_Query = state.GetEntityQuery(builder);
            builder.Reset();
            builder.WithAllRW<UniqueInputTickMap>();
            m_TickMapQuery = state.GetEntityQuery(builder);
            m_Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataHandle = state.GetBufferTypeHandle<Unity.NetCode.InputBufferData<EquipmentEventCounter>>(true);
            state.RequireForUpdate(m_Query);
            state.RequireForUpdate<UniqueInputTickMap>();
        }
        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            m_Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataHandle.Update(ref state);
            var job = new CompareJob
            {
                inputTypeHandle = m_Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataHandle,
                map = m_TickMapQuery.GetSingletonRW<UniqueInputTickMap>().ValueRW.Value
            };
            state.Dependency = job.ScheduleParallel(m_Query, state.Dependency);
        }
    }
}
