#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_BuildingObjectsSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
#define COMPONENT_HAS_GHOST_FIELDS
#define GHOST_COMPONENT_IS_BUFFER

using System;
using System.Runtime.CompilerServices;
using System.Diagnostics;
using Unity.Burst;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;

namespace Assembly_CSharp_Generated
{
    /// <summary>
    /// Auto-Generated struct implementing the IGhostSerializer and used to
    /// serialize/deserialize components and buffers.
    /// </summary>
    public partial struct Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer : IGhostSerializer
    {
        /// <summary>
        /// Internal compoment representation used for serialization/deserialization purpose.
        /// </summary>
        internal struct Snapshot
        {
            public int position_x;
            public int position_y;
            public int id;
            public int variantIndex;
            public int stateIndex;
            public float hitPoints;
            public float maxHitPoints;
        }
        /// <summary>The total number of bits used for the change mask.</summary>
        private const int ChangeMaskBits = 7;
        /// <summary>The number of bits used for the change mask.</summary>
        public int ChangeMaskSizeInBits => ChangeMaskBits;
        #if COMPONENT_HAS_GHOST_FIELDS
        /// <summary>Denote if fields are serialized or not.</summary>
        public bool HasGhostFields => true;
        /// <summary>The size in bytes of the Snasphot struct.</summary>
        public int SizeInSnapshot => UnsafeUtility.SizeOf<Snapshot>();
        #else
        /// <summary>Denote if fields are serialized or not.</summary>
        public bool HasGhostFields => false;
        /// <summary>The size in bytes of the Snasphot struct.</summary>
        public int SizeInSnapshot => 0;
        #endif

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.CopyToSnapshotGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void CopyToSnapshotGenerated(in GhostSerializerState serializerState, ref Snapshot snapshot, ref BuildingObjects component)
        {
                snapshot.position_x = (int) component.position.x;
                snapshot.position_y = (int) component.position.y;
                snapshot.id = (int) component.id;
                snapshot.variantIndex = (int) component.variantIndex;
                snapshot.stateIndex = (int) component.stateIndex;
                snapshot.hitPoints = component.hitPoints;
                snapshot.maxHitPoints = component.maxHitPoints;
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.CopyFromSnapshotGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void CopyFromSnapshotGenerated(in GhostDeserializerState deserializerState, ref BuildingObjects component,
            float snapshotInterpolationFactor, float snapshotInterpolationFactorRaw, ref Snapshot snapshotBefore, ref Snapshot snapshotAfter)
        {
                component.position.x = (int) snapshotBefore.position_x;
                component.position.y = (int) snapshotBefore.position_y;
                component.id = (int) snapshotBefore.id;
                component.variantIndex = (short) snapshotBefore.variantIndex;
                component.stateIndex = (short) snapshotBefore.stateIndex;
                component.hitPoints = snapshotBefore.hitPoints;
                component.maxHitPoints = snapshotBefore.maxHitPoints;
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.RestoreFromBackupGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void RestoreFromBackupGenerated(ref BuildingObjects component, ref BuildingObjects backup)
        {
            component.position.x = backup.position.x;
            component.position.y = backup.position.y;
            component.id = backup.id;
            component.variantIndex = backup.variantIndex;
            component.stateIndex = backup.stateIndex;
            component.hitPoints = backup.hitPoints;
            component.maxHitPoints = backup.maxHitPoints;
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.PredictDeltaGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void PredictDeltaGenerated(ref Snapshot snapshot, ref Snapshot baseline1, ref Snapshot baseline2,
            ref GhostDeltaPredictor predictor)
        {
            snapshot.position_x = predictor.PredictInt(snapshot.position_x, baseline1.position_x, baseline2.position_x);
            snapshot.position_y = predictor.PredictInt(snapshot.position_y, baseline1.position_y, baseline2.position_y);
            snapshot.id = predictor.PredictInt(snapshot.id, baseline1.id, baseline2.id);
            snapshot.variantIndex = predictor.PredictInt(snapshot.variantIndex, baseline1.variantIndex, baseline2.variantIndex);
            snapshot.stateIndex = predictor.PredictInt(snapshot.stateIndex, baseline1.stateIndex, baseline2.stateIndex);
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.CalculateChangeMaskGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void CalculateChangeMaskGenerated(ref Snapshot snapshot, ref Snapshot baseline,
            [NoAlias]IntPtr changeMaskData, int startOffset)
        {
            uint changeMask = 0;
            changeMask = (snapshot.position_x != baseline.position_x) ? 1u : 0;
            changeMask |= (snapshot.position_y != baseline.position_y) ? (1u<<1) : 0;
            changeMask |= (snapshot.id != baseline.id) ? (1u<<2) : 0;
            changeMask |= (snapshot.variantIndex != baseline.variantIndex) ? (1u<<3) : 0;
            changeMask |= (snapshot.stateIndex != baseline.stateIndex) ? (1u<<4) : 0;
            changeMask |= (snapshot.hitPoints != baseline.hitPoints) ? (1u<<5) : 0;
            changeMask |= (snapshot.maxHitPoints != baseline.maxHitPoints) ? (1u<<6) : 0;
            GhostComponentSerializer.CopyToChangeMask(changeMaskData, changeMask, startOffset + 0, 7);
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.SerializeGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void SerializeGenerated(ref Snapshot snapshot, ref Snapshot baseline,
            [NoAlias]IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.position_x, baseline.position_x, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.position_y, baseline.position_y, compressionModel);
            if ((changeMask & (1 << 2)) != 0)
                writer.WritePackedIntDelta(snapshot.id, baseline.id, compressionModel);
            if ((changeMask & (1 << 3)) != 0)
                writer.WritePackedIntDelta(snapshot.variantIndex, baseline.variantIndex, compressionModel);
            if ((changeMask & (1 << 4)) != 0)
                writer.WritePackedIntDelta(snapshot.stateIndex, baseline.stateIndex, compressionModel);
            if ((changeMask & (1 << 5)) != 0)
                writer.WritePackedFloatDelta(snapshot.hitPoints, baseline.hitPoints, compressionModel);
            if ((changeMask & (1 << 6)) != 0)
                writer.WritePackedFloatDelta(snapshot.maxHitPoints, baseline.maxHitPoints, compressionModel);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void SerializeCombinedGenerated(ref Snapshot snapshot, ref Snapshot baseline,
            [NoAlias]IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            uint changeMask = 0;
            changeMask = (snapshot.position_x != baseline.position_x) ? 1u : 0;
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.position_x, baseline.position_x, compressionModel);
            changeMask |= (snapshot.position_y != baseline.position_y) ? (1u<<1) : 0;
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.position_y, baseline.position_y, compressionModel);
            changeMask |= (snapshot.id != baseline.id) ? (1u<<2) : 0;
            if ((changeMask & (1 << 2)) != 0)
                writer.WritePackedIntDelta(snapshot.id, baseline.id, compressionModel);
            changeMask |= (snapshot.variantIndex != baseline.variantIndex) ? (1u<<3) : 0;
            if ((changeMask & (1 << 3)) != 0)
                writer.WritePackedIntDelta(snapshot.variantIndex, baseline.variantIndex, compressionModel);
            changeMask |= (snapshot.stateIndex != baseline.stateIndex) ? (1u<<4) : 0;
            if ((changeMask & (1 << 4)) != 0)
                writer.WritePackedIntDelta(snapshot.stateIndex, baseline.stateIndex, compressionModel);
            changeMask |= (snapshot.hitPoints != baseline.hitPoints) ? (1u<<5) : 0;
            if ((changeMask & (1 << 5)) != 0)
                writer.WritePackedFloatDelta(snapshot.hitPoints, baseline.hitPoints, compressionModel);
            changeMask |= (snapshot.maxHitPoints != baseline.maxHitPoints) ? (1u<<6) : 0;
            if ((changeMask & (1 << 6)) != 0)
                writer.WritePackedFloatDelta(snapshot.maxHitPoints, baseline.maxHitPoints, compressionModel);
            GhostComponentSerializer.CopyToChangeMask(changeMaskData, changeMask, startOffset + 0, 7);
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.DeserializeGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void DeserializeGenerated(ref DataStreamReader reader,
            in StreamCompressionModel compressionModel,
            IntPtr changeMaskData, int startOffset, ref Snapshot snapshot, ref Snapshot baseline)
        {
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                snapshot.position_x = reader.ReadPackedIntDelta(baseline.position_x, compressionModel);
            else
                snapshot.position_x = baseline.position_x;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.position_y = reader.ReadPackedIntDelta(baseline.position_y, compressionModel);
            else
                snapshot.position_y = baseline.position_y;
            if ((changeMask & (1 << 2)) != 0)
                snapshot.id = reader.ReadPackedIntDelta(baseline.id, compressionModel);
            else
                snapshot.id = baseline.id;
            if ((changeMask & (1 << 3)) != 0)
                snapshot.variantIndex = reader.ReadPackedIntDelta(baseline.variantIndex, compressionModel);
            else
                snapshot.variantIndex = baseline.variantIndex;
            if ((changeMask & (1 << 4)) != 0)
                snapshot.stateIndex = reader.ReadPackedIntDelta(baseline.stateIndex, compressionModel);
            else
                snapshot.stateIndex = baseline.stateIndex;
            if ((changeMask & (1 << 5)) != 0)
                snapshot.hitPoints = reader.ReadPackedFloatDelta(baseline.hitPoints, compressionModel);
            else
                snapshot.hitPoints = baseline.hitPoints;
            if ((changeMask & (1 << 6)) != 0)
                snapshot.maxHitPoints = reader.ReadPackedFloatDelta(baseline.maxHitPoints, compressionModel);
            else
                snapshot.maxHitPoints = baseline.maxHitPoints;
        }

#if UNITY_EDITOR || NETCODE_DEBUG
        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.ReportPredictionErrorsGenerated"/>
        static void ReportPredictionErrorsGenerated(in BuildingObjects component, in BuildingObjects backup, IntPtr errorsList,
            int errorsCount)
        {
            var errors = GhostComponentSerializer.ConvertToUnsafeList(errorsList, errorsCount);
            int errorIndex = 0;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.position.x - backup.position.x));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.position.y - backup.position.y));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.id - backup.id));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.variantIndex - backup.variantIndex));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.stateIndex - backup.stateIndex));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.hitPoints - backup.hitPoints));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.maxHitPoints - backup.maxHitPoints));
            ++errorIndex;
        }

        static internal int GetPredictionErrorNamesGenerated(ref FixedString512Bytes names)
        {
            var nameCount = 0;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".position.x");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".position.y");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".id");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".variantIndex");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".stateIndex");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".hitPoints");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".maxHitPoints");
            ++nameCount;
            return nameCount;
        }
#endif

        /// <inheritdoc cref="IGhostSerializer.CopyToSnapshot"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CopyToSnapshot(in GhostSerializerState serializerState, [NoAlias]IntPtr snapshot, [NoAlias][ReadOnly]IntPtr component)
        {
            CopyToSnapshotGenerated(serializerState, ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<BuildingObjects>(component));
        }

        /// <inheritdoc cref="IGhostSerializer.CopyToSnapshot"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CopyFromSnapshot(in GhostDeserializerState serializerState, [NoAlias]IntPtr component,
            float snapshotInterpolationFactor, float snapshotInterpolationFactorRaw, [NoAlias][ReadOnly]IntPtr snapshotBefore,
            [NoAlias][ReadOnly]IntPtr snapshotAfter)
        {
            CopyFromSnapshotGenerated(serializerState,
                ref GhostComponentSerializer.TypeCast<BuildingObjects>(component),
                snapshotInterpolationFactor,snapshotInterpolationFactorRaw,
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotBefore),
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotAfter));
        }

        /// <inheritdoc cref="IGhostSerializer.CalculateChangeMask"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CalculateChangeMask([NoAlias] [ReadOnly] IntPtr snapshot,
            [NoAlias] [ReadOnly] IntPtr baseline, [NoAlias] IntPtr changeMaskData, int startOffset)
        {
            CalculateChangeMaskGenerated(ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline),
                changeMaskData, startOffset);
        }

        /// <inheritdoc cref="IGhostSerializer.PredictDelta"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void PredictDelta([NoAlias] IntPtr snapshotData,
            [NoAlias] IntPtr baseline1Data, [NoAlias] IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline1 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1Data);
            ref var baseline2 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2Data);
            PredictDeltaGenerated(ref snapshot, ref baseline1, ref baseline2, ref predictor);
        }

        /// <inheritdoc cref="IGhostSerializer.SerializeWithPredictedBaseline"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SerializeWithPredictedBaseline([ReadOnly] [NoAlias] IntPtr snapshot,
            [ReadOnly] [NoAlias] IntPtr baseline0,
            [ReadOnly] [NoAlias] IntPtr baseline1,
            [ReadOnly] [NoAlias] IntPtr baseline2,
            ref GhostDeltaPredictor predictor,
            [NoAlias] [ReadOnly] IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            var baseline = GhostComponentSerializer.TypeCast<Snapshot>(baseline0);
            PredictDeltaGenerated(ref baseline,
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2),
                ref predictor);
            SerializeCombinedGenerated(
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref baseline,
                changeMaskData, startOffset,
                ref writer, compressionModel);
        }

        /// <inheritdoc cref="IGhostSerializer.SerializeCombined"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SerializeCombined([ReadOnly] [NoAlias] IntPtr snapshot,
            [ReadOnly] [NoAlias] IntPtr baseline,
            [NoAlias] [ReadOnly] IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            SerializeCombinedGenerated(
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline),
                changeMaskData, startOffset,
                ref writer, compressionModel);
        }

        /// <inheritdoc cref="IGhostSerializer.Serialize"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Serialize([ReadOnly] [NoAlias] IntPtr snapshot,
            [ReadOnly] [NoAlias] IntPtr baseline,
            [NoAlias] [ReadOnly] IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            SerializeGenerated(
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline),
                changeMaskData, startOffset,
                ref writer, compressionModel);
        }

        /// <inheritdoc cref="IGhostSerializer.Deserialize"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Deserialize(ref DataStreamReader reader, in StreamCompressionModel compressionModel,
            IntPtr changeMask,
            int startOffset, [NoAlias]IntPtr snapshot, [NoAlias][ReadOnly]IntPtr baseline)

        {
            DeserializeGenerated(ref reader, compressionModel, changeMask, startOffset,
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline));
        }

        /// <inheritdoc cref="IGhostSerializer.Deserialize"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void RestoreFromBackup([NoAlias] IntPtr component, [NoAlias] [ReadOnly] IntPtr backup)
        {
            RestoreFromBackupGenerated(
                ref GhostComponentSerializer.TypeCast<BuildingObjects>(component),
                ref GhostComponentSerializer.TypeCast<BuildingObjects>(backup));
        }

#if UNITY_EDITOR || NETCODE_DEBUG
        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.ReportPredictionErrorsGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void ReportPredictionErrors([NoAlias][ReadOnly]IntPtr component, [NoAlias][ReadOnly]IntPtr backup, IntPtr errorsList,
            int errorsCount)
        {
            ReportPredictionErrorsGenerated(GhostComponentSerializer.TypeCast<BuildingObjects>(component),
                GhostComponentSerializer.TypeCast<BuildingObjects>(backup), errorsList, errorsCount);
        }
#endif
    }

    //Registration
    [BurstCompile]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial struct Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer : IGhostSerializer
    {
        static internal GhostComponentSerializer.State GetState(ref SystemState state)
        {
            // This needs to be lazy initialized because otherwise there is a depenency on the static initialization order which breaks il2cpp builds, due to TypeManager not being initialized yet.
            // Also, Burst function pointer compilation can take a while.
            if (!s_StateInitialized)
            {
                s_State = new GhostComponentSerializer.State
                {
                    GhostFieldsHash = 1966819302090705106,
                    ComponentType = ComponentType.ReadWrite<BuildingObjects>(),
                    ComponentSize = UnsafeUtility.SizeOf<BuildingObjects>(),
#if COMPONENT_HAS_GHOST_FIELDS
                    SnapshotSize = UnsafeUtility.SizeOf<Snapshot>(),
#else
                    SnapshotSize = 0,
#endif
                    ChangeMaskBits = 7,
                    PrefabType = GhostPrefabType.All,
                    SendMask = GhostSendType.AllClients,
                    SendToOwner = SendToOwnerType.All,
                    VariantHash = 13954076973311546972,
                    SerializationStrategyIndex = -1,
                    SerializesEnabledBit = 0,
#if UNITY_EDITOR || NETCODE_DEBUG
                    ProfilerMarker = new Unity.Profiling.ProfilerMarker("BuildingObjects"),
                    VariantTypeFullNameHash = TypeHash.FNV1A64("BuildingObjects")
#endif
                };
                // UnsafeUtility.SizeOf<T> reports 1 with zero-sized components.
                if (s_State.ComponentType.IsZeroSized)
                    s_State.ComponentSize = 0;

#if UNITY_EDITOR || NETCODE_DEBUG
                s_State.ProfilerMarker.Begin();
                var innerMarker = new Unity.Profiling.ProfilerMarker("Assembly_CSharp_Generated_BuildingObjects");
                innerMarker.Begin();
#endif
                s_StateInitialized = SetupFunctionPointers(ref s_State, ref state);
                //TODO: DOTS-7926 we should understand why we have in some cases a StackOverflowException.
                //UNCOMMENT THIS LINE TO DEBUG IF A BIG COMPONENT MAY BE CAUSING A STACK OVERFLOW
                // const int maxSizeToAvoidStackOverflow = 4_500;
                // if (s_State.ComponentSize > maxSizeToAvoidStackOverflow)
                // {
                //     UnityEngine.Debug.LogWarning($"The type '{s_State.ComponentType}' is very large ({s_State.ComponentSize} bytes)! There is a risk of StackOverflowExceptions in the Serializers at roughly {maxSizeToAvoidStackOverflow} bytes! Remove large fields.");
                // }
#if UNITY_EDITOR || NETCODE_DEBUG
                s_State.NumPredictionErrors = GetPredictionErrorNamesGenerated(ref s_State.PredictionErrorNames);
#endif

#if UNITY_EDITOR || NETCODE_DEBUG
                innerMarker.End();
                s_State.ProfilerMarker.End();
#endif
            }
            return s_State;
        }

        private static bool s_StateInitialized;
        private static GhostComponentSerializer.State s_State;

        private static bool SetupFunctionPointers(ref GhostComponentSerializer.State state,
            ref SystemState systemState)
        {
            // Optimization: Creating burst functions is expensive.
            // We don't need to do it in literally any other words as they're never called.
            if ((systemState.WorldUnmanaged.Flags & WorldFlags.GameServer) != WorldFlags.GameServer
                && (systemState.WorldUnmanaged.Flags & WorldFlags.GameClient) != WorldFlags.GameClient
                && (systemState.WorldUnmanaged.Flags & WorldFlags.GameThinClient) != WorldFlags.GameThinClient)
                return false;

#if !GHOST_COMPONENT_IS_BUFFER
            state.PostSerialize = new PortableFunctionPointer<GhostComponentSerializer.PostSerializeDelegate>(
                AOT_PostSerialize);
            state.Serialize = new PortableFunctionPointer<GhostComponentSerializer.SerializeDelegate>(
                AOT_Serialize);
#else
            state.PostSerializeBuffer = new PortableFunctionPointer<GhostComponentSerializer.PostSerializeBufferDelegate>(
                AOT_PostSerializeBuffer);
            state.SerializeBuffer = new PortableFunctionPointer<GhostComponentSerializer.SerializeBufferDelegate>(
                AOT_SerializeBuffer);
#endif
            state.CopyFromSnapshot = new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(
                AOT_CopyFromSnapshot);
            state.CopyToSnapshot = new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(
                AOT_CopyToSnapshot);
            state.RestoreFromBackup = new PortableFunctionPointer<GhostComponentSerializer.RestoreFromBackupDelegate>(
                AOT_RestoreFromBackup);
            state.PredictDelta = new PortableFunctionPointer<GhostComponentSerializer.PredictDeltaDelegate>(
                AOT_PredictDelta);
            state.Deserialize = new PortableFunctionPointer<GhostComponentSerializer.DeserializeDelegate>(
                AOT_Deserialize);
#if UNITY_EDITOR || NETCODE_DEBUG
            state.ReportPredictionErrors = new PortableFunctionPointer<GhostComponentSerializer.ReportPredictionErrorsDelegate>(
                AOT_ReportPredictionErrors);
#endif
            return true;
        }

#if !GHOST_COMPONENT_IS_BUFFER
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.PostSerializeDelegate))]
        private static void AOT_PostSerialize(IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            int maskOffsetInBits,
            int count, IntPtr baselines, ref DataStreamWriter writer,
            ref StreamCompressionModel compressionModel,
            IntPtr entityStartBit)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer);
            Unity.NetCode.ComponentSerializationHelper<
                    BuildingObjects,
                    Snapshot,
                    Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer
            >.PostSerializeComponents(serializer,
                snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, count, baselines,
                ref writer, ref compressionModel, entityStartBit);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void AOT_Serialize([NoAlias]IntPtr stateData,
            IntPtr snapshotData, int snapshotOffset, int snapshotStride, int maskOffsetInBits,
            IntPtr componentData, int count, IntPtr baselines,
            ref DataStreamWriter writer, ref StreamCompressionModel compressionModel, IntPtr entityStartBit)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer);
            Unity.NetCode.ComponentSerializationHelper<
                    BuildingObjects,
                    Snapshot,
                    Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer
            >.SerializeComponents(serializer, stateData, snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, componentData, count, baselines, ref writer, compressionModel, entityStartBit);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
#else
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.PostSerializeDelegate))]
        private static void AOT_PostSerializeBuffer(IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            int maskOffsetInBits, int changeMaskBits, int count, IntPtr baselines,
            ref DataStreamWriter writer, ref StreamCompressionModel compressionModel,
            IntPtr entityStartBit, IntPtr snapshotDynamicDataPtr, IntPtr dynamicSizePerEntity, int dynamicSnapshotMaxOffset)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer);
            Unity.NetCode.BufferSerializationHelper<
                BuildingObjects,
                Snapshot,
                Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer
            >.PostSerializeBuffers(snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, changeMaskBits, count, baselines,
                ref writer, compressionModel, entityStartBit, snapshotDynamicDataPtr, dynamicSizePerEntity, dynamicSnapshotMaxOffset,
                serializer);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void AOT_SerializeBuffer(IntPtr stateData,
            IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            int maskOffsetInBits, int changeMaskBits,
            IntPtr componentData, IntPtr componentDataLen, int count, [NoAlias]IntPtr baselines,
            ref DataStreamWriter writer, ref StreamCompressionModel compressionModel,
            IntPtr entityStartBit, IntPtr snapshotDynamicDataPtr, ref int dynamicSnapshotDataOffset,
            IntPtr dynamicSizePerEntity, int dynamicSnapshotMaxOffset)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer);
            Unity.NetCode.BufferSerializationHelper<
                BuildingObjects,
                Snapshot,
                Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer
            >.SerializeBuffers(stateData, snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, changeMaskBits,
                componentData, componentDataLen, count, baselines, ref writer, compressionModel, entityStartBit, snapshotDynamicDataPtr,
                ref dynamicSnapshotDataOffset, dynamicSizePerEntity, dynamicSnapshotMaxOffset, serializer);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
#endif
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void AOT_CopyToSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            IntPtr componentData, int componentStride, int count)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer);
#if !GHOST_COMPONENT_IS_BUFFER
            Unity.NetCode.ComponentSerializationHelper<
                    BuildingObjects,
                    Snapshot,
                    Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer
            >.CopyComponentsToSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#else
            Unity.NetCode.BufferSerializationHelper<
                BuildingObjects,
                Snapshot,
                Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer
            >.CopyBuffersToSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#endif
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void AOT_CopyFromSnapshot(IntPtr stateData, IntPtr snapshotData,
            int snapshotOffset, int snapshotStride,
            IntPtr componentData, int componentStride, int count)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer);
#if !GHOST_COMPONENT_IS_BUFFER
            Unity.NetCode.ComponentSerializationHelper<
                BuildingObjects,
                Snapshot,
                Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer
            >.CopyComponentsFromSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#else
            Unity.NetCode.BufferSerializationHelper<
                BuildingObjects,
                Snapshot,
                Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer
            >.CopyBuffersFromSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#endif
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.RestoreFromBackupDelegate))]
        private static void AOT_RestoreFromBackup(IntPtr componentData, IntPtr backupData)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer);
            serializer.RestoreFromBackup(componentData, backupData);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.PredictDeltaDelegate))]
        private static void AOT_PredictDelta(IntPtr snapshotData,
            IntPtr baseline1Data, IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer);
            serializer.PredictDelta(snapshotData, baseline1Data, baseline2Data, ref predictor);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.DeserializeDelegate))]
        private static void AOT_Deserialize(IntPtr snapshotData, IntPtr baselineData,
            ref DataStreamReader reader, ref StreamCompressionModel compressionModel,
            IntPtr changeMaskData, int startOffset)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer);
            serializer.Deserialize(ref reader, compressionModel, changeMaskData, startOffset, snapshotData, baselineData);
#endif
        }
#if UNITY_EDITOR || NETCODE_DEBUG
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.ReportPredictionErrorsDelegate))]
        private static void AOT_ReportPredictionErrors(IntPtr componentData, IntPtr backupData,
            IntPtr errorsList, int errorsCount)
        {
            var serializer = default(Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer);
            serializer.ReportPredictionErrors(componentData, backupData, errorsList, errorsCount);
        }
#endif
    }
}
