#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/2062241058503599662_PlayerInputPlayerInputInputBufferDataSerializer.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
#define COMPONENT_HAS_GHOST_FIELDS
#define GHOST_COMPONENT_IS_BUFFER

using System;
using System.Runtime.CompilerServices;
using System.Diagnostics;
using Unity.Burst;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;

namespace Assembly_CSharp_Generated
{
    /// <summary>
    /// Auto-Generated struct implementing the IGhostSerializer and used to
    /// serialize/deserialize components and buffers.
    /// </summary>
    public partial struct Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer : IGhostSerializer
    {
        /// <summary>
        /// Internal compoment representation used for serialization/deserialization purpose.
        /// </summary>
        internal struct Snapshot
        {
            public float InternalInput_movementDirection_x;
            public float InternalInput_movementDirection_y;
            public float InternalInput_sightDirection_x;
            public float InternalInput_sightDirection_y;
            public uint InternalInput_rightButton_Count;
            public uint InternalInput_leftButton_Count;
            public uint InternalInput_reloadButton_Count;
            public uint InternalInput_unloadButton_Count;
            public int InternalInput_slotInHand;
            public int InternalInput_ammoSelectedIndex;
            public uint InternalInput_dataTick;
            public uint Tick;
        }
        /// <summary>The total number of bits used for the change mask.</summary>
        private const int ChangeMaskBits = 10;
        /// <summary>The number of bits used for the change mask.</summary>
        public int ChangeMaskSizeInBits => ChangeMaskBits;
        #if COMPONENT_HAS_GHOST_FIELDS
        /// <summary>Denote if fields are serialized or not.</summary>
        public bool HasGhostFields => true;
        /// <summary>The size in bytes of the Snasphot struct.</summary>
        public int SizeInSnapshot => UnsafeUtility.SizeOf<Snapshot>();
        #else
        /// <summary>Denote if fields are serialized or not.</summary>
        public bool HasGhostFields => false;
        /// <summary>The size in bytes of the Snasphot struct.</summary>
        public int SizeInSnapshot => 0;
        #endif

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.CopyToSnapshotGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void CopyToSnapshotGenerated(in GhostSerializerState serializerState, ref Snapshot snapshot, ref Unity.NetCode.InputBufferData<PlayerInput> component)
        {
                snapshot.InternalInput_movementDirection_x = component.InternalInput.movementDirection.x;
                snapshot.InternalInput_movementDirection_y = component.InternalInput.movementDirection.y;
                snapshot.InternalInput_sightDirection_x = component.InternalInput.sightDirection.x;
                snapshot.InternalInput_sightDirection_y = component.InternalInput.sightDirection.y;
                snapshot.InternalInput_rightButton_Count = (uint)component.InternalInput.rightButton.Count;
                snapshot.InternalInput_leftButton_Count = (uint)component.InternalInput.leftButton.Count;
                snapshot.InternalInput_reloadButton_Count = (uint)component.InternalInput.reloadButton.Count;
                snapshot.InternalInput_unloadButton_Count = (uint)component.InternalInput.unloadButton.Count;
                snapshot.InternalInput_slotInHand = (int) component.InternalInput.slotInHand;
                snapshot.InternalInput_ammoSelectedIndex = (int) component.InternalInput.ammoSelectedIndex;
                snapshot.InternalInput_dataTick = component.InternalInput.dataTick.SerializedData;
                snapshot.Tick = component.Tick.SerializedData;
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.CopyFromSnapshotGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void CopyFromSnapshotGenerated(in GhostDeserializerState deserializerState, ref Unity.NetCode.InputBufferData<PlayerInput> component,
            float snapshotInterpolationFactor, float snapshotInterpolationFactorRaw, ref Snapshot snapshotBefore, ref Snapshot snapshotAfter)
        {
                component.InternalInput.movementDirection = new float2(snapshotBefore.InternalInput_movementDirection_x, snapshotBefore.InternalInput_movementDirection_y);
                component.InternalInput.sightDirection = new float2(snapshotBefore.InternalInput_sightDirection_x, snapshotBefore.InternalInput_sightDirection_y);
                component.InternalInput.rightButton.Count = (uint) snapshotBefore.InternalInput_rightButton_Count;
                component.InternalInput.leftButton.Count = (uint) snapshotBefore.InternalInput_leftButton_Count;
                component.InternalInput.reloadButton.Count = (uint) snapshotBefore.InternalInput_reloadButton_Count;
                component.InternalInput.unloadButton.Count = (uint) snapshotBefore.InternalInput_unloadButton_Count;
                component.InternalInput.slotInHand = (int) snapshotBefore.InternalInput_slotInHand;
                component.InternalInput.ammoSelectedIndex = (int) snapshotBefore.InternalInput_ammoSelectedIndex;
                component.InternalInput.dataTick = new Unity.NetCode.NetworkTick{SerializedData = snapshotBefore.InternalInput_dataTick};
                component.Tick = new Unity.NetCode.NetworkTick{SerializedData = snapshotBefore.Tick};
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.RestoreFromBackupGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void RestoreFromBackupGenerated(ref Unity.NetCode.InputBufferData<PlayerInput> component, ref Unity.NetCode.InputBufferData<PlayerInput> backup)
        {
            component.InternalInput.movementDirection.x = backup.InternalInput.movementDirection.x;
            component.InternalInput.movementDirection.y = backup.InternalInput.movementDirection.y;
            component.InternalInput.sightDirection.x = backup.InternalInput.sightDirection.x;
            component.InternalInput.sightDirection.y = backup.InternalInput.sightDirection.y;
            component.InternalInput.rightButton.Count = backup.InternalInput.rightButton.Count;
            component.InternalInput.leftButton.Count = backup.InternalInput.leftButton.Count;
            component.InternalInput.reloadButton.Count = backup.InternalInput.reloadButton.Count;
            component.InternalInput.unloadButton.Count = backup.InternalInput.unloadButton.Count;
            component.InternalInput.slotInHand = backup.InternalInput.slotInHand;
            component.InternalInput.ammoSelectedIndex = backup.InternalInput.ammoSelectedIndex;
            component.InternalInput.dataTick = backup.InternalInput.dataTick;
            component.Tick = backup.Tick;
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.PredictDeltaGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void PredictDeltaGenerated(ref Snapshot snapshot, ref Snapshot baseline1, ref Snapshot baseline2,
            ref GhostDeltaPredictor predictor)
        {
            snapshot.InternalInput_rightButton_Count = (uint)predictor.PredictInt((int)snapshot.InternalInput_rightButton_Count, (int)baseline1.InternalInput_rightButton_Count, (int)baseline2.InternalInput_rightButton_Count);
            snapshot.InternalInput_leftButton_Count = (uint)predictor.PredictInt((int)snapshot.InternalInput_leftButton_Count, (int)baseline1.InternalInput_leftButton_Count, (int)baseline2.InternalInput_leftButton_Count);
            snapshot.InternalInput_reloadButton_Count = (uint)predictor.PredictInt((int)snapshot.InternalInput_reloadButton_Count, (int)baseline1.InternalInput_reloadButton_Count, (int)baseline2.InternalInput_reloadButton_Count);
            snapshot.InternalInput_unloadButton_Count = (uint)predictor.PredictInt((int)snapshot.InternalInput_unloadButton_Count, (int)baseline1.InternalInput_unloadButton_Count, (int)baseline2.InternalInput_unloadButton_Count);
            snapshot.InternalInput_slotInHand = predictor.PredictInt(snapshot.InternalInput_slotInHand, baseline1.InternalInput_slotInHand, baseline2.InternalInput_slotInHand);
            snapshot.InternalInput_ammoSelectedIndex = predictor.PredictInt(snapshot.InternalInput_ammoSelectedIndex, baseline1.InternalInput_ammoSelectedIndex, baseline2.InternalInput_ammoSelectedIndex);
            snapshot.InternalInput_dataTick = (uint)predictor.PredictInt((int)snapshot.InternalInput_dataTick, (int)baseline1.InternalInput_dataTick, (int)baseline2.InternalInput_dataTick);
            snapshot.Tick = (uint)predictor.PredictInt((int)snapshot.Tick, (int)baseline1.Tick, (int)baseline2.Tick);
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.CalculateChangeMaskGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void CalculateChangeMaskGenerated(ref Snapshot snapshot, ref Snapshot baseline,
            [NoAlias]IntPtr changeMaskData, int startOffset)
        {
            uint changeMask = 0;
            changeMask = (snapshot.InternalInput_movementDirection_x != baseline.InternalInput_movementDirection_x) ? 1u : 0;
            changeMask |= (snapshot.InternalInput_movementDirection_y != baseline.InternalInput_movementDirection_y) ? (1u<<0) : 0;
            changeMask |= (snapshot.InternalInput_sightDirection_x != baseline.InternalInput_sightDirection_x) ? (1u<<1) : 0;
            changeMask |= (snapshot.InternalInput_sightDirection_y != baseline.InternalInput_sightDirection_y) ? (1u<<1) : 0;
            changeMask |= (snapshot.InternalInput_rightButton_Count != baseline.InternalInput_rightButton_Count) ? (1u<<2) : 0;
            changeMask |= (snapshot.InternalInput_leftButton_Count != baseline.InternalInput_leftButton_Count) ? (1u<<3) : 0;
            changeMask |= (snapshot.InternalInput_reloadButton_Count != baseline.InternalInput_reloadButton_Count) ? (1u<<4) : 0;
            changeMask |= (snapshot.InternalInput_unloadButton_Count != baseline.InternalInput_unloadButton_Count) ? (1u<<5) : 0;
            changeMask |= (snapshot.InternalInput_slotInHand != baseline.InternalInput_slotInHand) ? (1u<<6) : 0;
            changeMask |= (snapshot.InternalInput_ammoSelectedIndex != baseline.InternalInput_ammoSelectedIndex) ? (1u<<7) : 0;
            changeMask |= (snapshot.InternalInput_dataTick != baseline.InternalInput_dataTick) ? (1u<<8) : 0;
            changeMask |= (snapshot.Tick != baseline.Tick) ? (1u<<9) : 0;
            GhostComponentSerializer.CopyToChangeMask(changeMaskData, changeMask, startOffset + 0, 10);
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.SerializeGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void SerializeGenerated(ref Snapshot snapshot, ref Snapshot baseline,
            [NoAlias]IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedFloatDelta(snapshot.InternalInput_movementDirection_x, baseline.InternalInput_movementDirection_x, compressionModel);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedFloatDelta(snapshot.InternalInput_movementDirection_y, baseline.InternalInput_movementDirection_y, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedFloatDelta(snapshot.InternalInput_sightDirection_x, baseline.InternalInput_sightDirection_x, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedFloatDelta(snapshot.InternalInput_sightDirection_y, baseline.InternalInput_sightDirection_y, compressionModel);
            if ((changeMask & (1 << 2)) != 0)
                writer.WritePackedUIntDelta(snapshot.InternalInput_rightButton_Count, baseline.InternalInput_rightButton_Count, compressionModel);
            if ((changeMask & (1 << 3)) != 0)
                writer.WritePackedUIntDelta(snapshot.InternalInput_leftButton_Count, baseline.InternalInput_leftButton_Count, compressionModel);
            if ((changeMask & (1 << 4)) != 0)
                writer.WritePackedUIntDelta(snapshot.InternalInput_reloadButton_Count, baseline.InternalInput_reloadButton_Count, compressionModel);
            if ((changeMask & (1 << 5)) != 0)
                writer.WritePackedUIntDelta(snapshot.InternalInput_unloadButton_Count, baseline.InternalInput_unloadButton_Count, compressionModel);
            if ((changeMask & (1 << 6)) != 0)
                writer.WritePackedIntDelta(snapshot.InternalInput_slotInHand, baseline.InternalInput_slotInHand, compressionModel);
            if ((changeMask & (1 << 7)) != 0)
                writer.WritePackedIntDelta(snapshot.InternalInput_ammoSelectedIndex, baseline.InternalInput_ammoSelectedIndex, compressionModel);
            if ((changeMask & (1 << 8)) != 0)
                writer.WritePackedUIntDelta(snapshot.InternalInput_dataTick, baseline.InternalInput_dataTick, compressionModel);
            if ((changeMask & (1 << 9)) != 0)
                writer.WritePackedUIntDelta(snapshot.Tick, baseline.Tick, compressionModel);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void SerializeCombinedGenerated(ref Snapshot snapshot, ref Snapshot baseline,
            [NoAlias]IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            uint changeMask = 0;
            changeMask = (snapshot.InternalInput_movementDirection_x != baseline.InternalInput_movementDirection_x) ? 1u : 0;
            changeMask |= (snapshot.InternalInput_movementDirection_y != baseline.InternalInput_movementDirection_y) ? (1u<<0) : 0;
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedFloatDelta(snapshot.InternalInput_movementDirection_x, baseline.InternalInput_movementDirection_x, compressionModel);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedFloatDelta(snapshot.InternalInput_movementDirection_y, baseline.InternalInput_movementDirection_y, compressionModel);
            changeMask |= (snapshot.InternalInput_sightDirection_x != baseline.InternalInput_sightDirection_x) ? (1u<<1) : 0;
            changeMask |= (snapshot.InternalInput_sightDirection_y != baseline.InternalInput_sightDirection_y) ? (1u<<1) : 0;
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedFloatDelta(snapshot.InternalInput_sightDirection_x, baseline.InternalInput_sightDirection_x, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedFloatDelta(snapshot.InternalInput_sightDirection_y, baseline.InternalInput_sightDirection_y, compressionModel);
            changeMask |= (snapshot.InternalInput_rightButton_Count != baseline.InternalInput_rightButton_Count) ? (1u<<2) : 0;
            if ((changeMask & (1 << 2)) != 0)
                writer.WritePackedUIntDelta(snapshot.InternalInput_rightButton_Count, baseline.InternalInput_rightButton_Count, compressionModel);
            changeMask |= (snapshot.InternalInput_leftButton_Count != baseline.InternalInput_leftButton_Count) ? (1u<<3) : 0;
            if ((changeMask & (1 << 3)) != 0)
                writer.WritePackedUIntDelta(snapshot.InternalInput_leftButton_Count, baseline.InternalInput_leftButton_Count, compressionModel);
            changeMask |= (snapshot.InternalInput_reloadButton_Count != baseline.InternalInput_reloadButton_Count) ? (1u<<4) : 0;
            if ((changeMask & (1 << 4)) != 0)
                writer.WritePackedUIntDelta(snapshot.InternalInput_reloadButton_Count, baseline.InternalInput_reloadButton_Count, compressionModel);
            changeMask |= (snapshot.InternalInput_unloadButton_Count != baseline.InternalInput_unloadButton_Count) ? (1u<<5) : 0;
            if ((changeMask & (1 << 5)) != 0)
                writer.WritePackedUIntDelta(snapshot.InternalInput_unloadButton_Count, baseline.InternalInput_unloadButton_Count, compressionModel);
            changeMask |= (snapshot.InternalInput_slotInHand != baseline.InternalInput_slotInHand) ? (1u<<6) : 0;
            if ((changeMask & (1 << 6)) != 0)
                writer.WritePackedIntDelta(snapshot.InternalInput_slotInHand, baseline.InternalInput_slotInHand, compressionModel);
            changeMask |= (snapshot.InternalInput_ammoSelectedIndex != baseline.InternalInput_ammoSelectedIndex) ? (1u<<7) : 0;
            if ((changeMask & (1 << 7)) != 0)
                writer.WritePackedIntDelta(snapshot.InternalInput_ammoSelectedIndex, baseline.InternalInput_ammoSelectedIndex, compressionModel);
            changeMask |= (snapshot.InternalInput_dataTick != baseline.InternalInput_dataTick) ? (1u<<8) : 0;
            if ((changeMask & (1 << 8)) != 0)
                writer.WritePackedUIntDelta(snapshot.InternalInput_dataTick, baseline.InternalInput_dataTick, compressionModel);
            changeMask |= (snapshot.Tick != baseline.Tick) ? (1u<<9) : 0;
            if ((changeMask & (1 << 9)) != 0)
                writer.WritePackedUIntDelta(snapshot.Tick, baseline.Tick, compressionModel);
            GhostComponentSerializer.CopyToChangeMask(changeMaskData, changeMask, startOffset + 0, 10);
        }

        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.DeserializeGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void DeserializeGenerated(ref DataStreamReader reader,
            in StreamCompressionModel compressionModel,
            IntPtr changeMaskData, int startOffset, ref Snapshot snapshot, ref Snapshot baseline)
        {
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                snapshot.InternalInput_movementDirection_x = reader.ReadPackedFloatDelta(baseline.InternalInput_movementDirection_x, compressionModel);
            else
                snapshot.InternalInput_movementDirection_x = baseline.InternalInput_movementDirection_x;
            if ((changeMask & (1 << 0)) != 0)
                snapshot.InternalInput_movementDirection_y = reader.ReadPackedFloatDelta(baseline.InternalInput_movementDirection_y, compressionModel);
            else
                snapshot.InternalInput_movementDirection_y = baseline.InternalInput_movementDirection_y;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.InternalInput_sightDirection_x = reader.ReadPackedFloatDelta(baseline.InternalInput_sightDirection_x, compressionModel);
            else
                snapshot.InternalInput_sightDirection_x = baseline.InternalInput_sightDirection_x;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.InternalInput_sightDirection_y = reader.ReadPackedFloatDelta(baseline.InternalInput_sightDirection_y, compressionModel);
            else
                snapshot.InternalInput_sightDirection_y = baseline.InternalInput_sightDirection_y;
            if ((changeMask & (1 << 2)) != 0)
                snapshot.InternalInput_rightButton_Count = reader.ReadPackedUIntDelta(baseline.InternalInput_rightButton_Count, compressionModel);
            else
                snapshot.InternalInput_rightButton_Count = baseline.InternalInput_rightButton_Count;
            if ((changeMask & (1 << 3)) != 0)
                snapshot.InternalInput_leftButton_Count = reader.ReadPackedUIntDelta(baseline.InternalInput_leftButton_Count, compressionModel);
            else
                snapshot.InternalInput_leftButton_Count = baseline.InternalInput_leftButton_Count;
            if ((changeMask & (1 << 4)) != 0)
                snapshot.InternalInput_reloadButton_Count = reader.ReadPackedUIntDelta(baseline.InternalInput_reloadButton_Count, compressionModel);
            else
                snapshot.InternalInput_reloadButton_Count = baseline.InternalInput_reloadButton_Count;
            if ((changeMask & (1 << 5)) != 0)
                snapshot.InternalInput_unloadButton_Count = reader.ReadPackedUIntDelta(baseline.InternalInput_unloadButton_Count, compressionModel);
            else
                snapshot.InternalInput_unloadButton_Count = baseline.InternalInput_unloadButton_Count;
            if ((changeMask & (1 << 6)) != 0)
                snapshot.InternalInput_slotInHand = reader.ReadPackedIntDelta(baseline.InternalInput_slotInHand, compressionModel);
            else
                snapshot.InternalInput_slotInHand = baseline.InternalInput_slotInHand;
            if ((changeMask & (1 << 7)) != 0)
                snapshot.InternalInput_ammoSelectedIndex = reader.ReadPackedIntDelta(baseline.InternalInput_ammoSelectedIndex, compressionModel);
            else
                snapshot.InternalInput_ammoSelectedIndex = baseline.InternalInput_ammoSelectedIndex;
            if ((changeMask & (1 << 8)) != 0)
                snapshot.InternalInput_dataTick = reader.ReadPackedUIntDelta(baseline.InternalInput_dataTick, compressionModel);
            else
                snapshot.InternalInput_dataTick = baseline.InternalInput_dataTick;
            if ((changeMask & (1 << 9)) != 0)
                snapshot.Tick = reader.ReadPackedUIntDelta(baseline.Tick, compressionModel);
            else
                snapshot.Tick = baseline.Tick;
        }

#if UNITY_EDITOR || NETCODE_DEBUG
        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.ReportPredictionErrorsGenerated"/>
        static void ReportPredictionErrorsGenerated(in Unity.NetCode.InputBufferData<PlayerInput> component, in Unity.NetCode.InputBufferData<PlayerInput> backup, IntPtr errorsList,
            int errorsCount)
        {
            var errors = GhostComponentSerializer.ConvertToUnsafeList(errorsList, errorsCount);
            int errorIndex = 0;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.InternalInput.movementDirection, backup.InternalInput.movementDirection));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.InternalInput.sightDirection, backup.InternalInput.sightDirection));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex],
                (component.InternalInput.rightButton.Count > backup.InternalInput.rightButton.Count) ?
                (component.InternalInput.rightButton.Count - backup.InternalInput.rightButton.Count) :
                (backup.InternalInput.rightButton.Count - component.InternalInput.rightButton.Count));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex],
                (component.InternalInput.leftButton.Count > backup.InternalInput.leftButton.Count) ?
                (component.InternalInput.leftButton.Count - backup.InternalInput.leftButton.Count) :
                (backup.InternalInput.leftButton.Count - component.InternalInput.leftButton.Count));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex],
                (component.InternalInput.reloadButton.Count > backup.InternalInput.reloadButton.Count) ?
                (component.InternalInput.reloadButton.Count - backup.InternalInput.reloadButton.Count) :
                (backup.InternalInput.reloadButton.Count - component.InternalInput.reloadButton.Count));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex],
                (component.InternalInput.unloadButton.Count > backup.InternalInput.unloadButton.Count) ?
                (component.InternalInput.unloadButton.Count - backup.InternalInput.unloadButton.Count) :
                (backup.InternalInput.unloadButton.Count - component.InternalInput.unloadButton.Count));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.InternalInput.slotInHand - backup.InternalInput.slotInHand));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.InternalInput.ammoSelectedIndex - backup.InternalInput.ammoSelectedIndex));
            ++errorIndex;
            {
            int tickErr = 0;
            if (component.InternalInput.dataTick.IsValid != backup.InternalInput.dataTick.IsValid)
            {
                // TODO: what is a good value for this?
                tickErr = 100;
            }
            else if (component.InternalInput.dataTick.IsValid)
                tickErr = math.abs(component.InternalInput.dataTick.TicksSince(backup.InternalInput.dataTick));
            errors[errorIndex] = math.max(errors[errorIndex], tickErr);
            ++errorIndex;
            }
            {
            int tickErr = 0;
            if (component.Tick.IsValid != backup.Tick.IsValid)
            {
                // TODO: what is a good value for this?
                tickErr = 100;
            }
            else if (component.Tick.IsValid)
                tickErr = math.abs(component.Tick.TicksSince(backup.Tick));
            errors[errorIndex] = math.max(errors[errorIndex], tickErr);
            ++errorIndex;
            }
        }

        static internal int GetPredictionErrorNamesGenerated(ref FixedString512Bytes names)
        {
            var nameCount = 0;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".InternalInput.movementDirection");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".InternalInput.sightDirection");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".InternalInput.rightButton.Count");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".InternalInput.leftButton.Count");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".InternalInput.reloadButton.Count");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".InternalInput.unloadButton.Count");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".InternalInput.slotInHand");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".InternalInput.ammoSelectedIndex");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".InternalInput.dataTick");
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32Bytes(","));
            names.Append((FixedString512Bytes)".Tick");
            ++nameCount;
            return nameCount;
        }
#endif

        /// <inheritdoc cref="IGhostSerializer.CopyToSnapshot"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CopyToSnapshot(in GhostSerializerState serializerState, [NoAlias]IntPtr snapshot, [NoAlias][ReadOnly]IntPtr component)
        {
            CopyToSnapshotGenerated(serializerState, ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Unity.NetCode.InputBufferData<PlayerInput>>(component));
        }

        /// <inheritdoc cref="IGhostSerializer.CopyToSnapshot"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CopyFromSnapshot(in GhostDeserializerState serializerState, [NoAlias]IntPtr component,
            float snapshotInterpolationFactor, float snapshotInterpolationFactorRaw, [NoAlias][ReadOnly]IntPtr snapshotBefore,
            [NoAlias][ReadOnly]IntPtr snapshotAfter)
        {
            CopyFromSnapshotGenerated(serializerState,
                ref GhostComponentSerializer.TypeCast<Unity.NetCode.InputBufferData<PlayerInput>>(component),
                snapshotInterpolationFactor,snapshotInterpolationFactorRaw,
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotBefore),
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotAfter));
        }

        /// <inheritdoc cref="IGhostSerializer.CalculateChangeMask"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CalculateChangeMask([NoAlias] [ReadOnly] IntPtr snapshot,
            [NoAlias] [ReadOnly] IntPtr baseline, [NoAlias] IntPtr changeMaskData, int startOffset)
        {
            CalculateChangeMaskGenerated(ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline),
                changeMaskData, startOffset);
        }

        /// <inheritdoc cref="IGhostSerializer.PredictDelta"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void PredictDelta([NoAlias] IntPtr snapshotData,
            [NoAlias] IntPtr baseline1Data, [NoAlias] IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline1 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1Data);
            ref var baseline2 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2Data);
            PredictDeltaGenerated(ref snapshot, ref baseline1, ref baseline2, ref predictor);
        }

        /// <inheritdoc cref="IGhostSerializer.SerializeWithPredictedBaseline"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SerializeWithPredictedBaseline([ReadOnly] [NoAlias] IntPtr snapshot,
            [ReadOnly] [NoAlias] IntPtr baseline0,
            [ReadOnly] [NoAlias] IntPtr baseline1,
            [ReadOnly] [NoAlias] IntPtr baseline2,
            ref GhostDeltaPredictor predictor,
            [NoAlias] [ReadOnly] IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            var baseline = GhostComponentSerializer.TypeCast<Snapshot>(baseline0);
            PredictDeltaGenerated(ref baseline,
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2),
                ref predictor);
            SerializeCombinedGenerated(
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref baseline,
                changeMaskData, startOffset,
                ref writer, compressionModel);
        }

        /// <inheritdoc cref="IGhostSerializer.SerializeCombined"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SerializeCombined([ReadOnly] [NoAlias] IntPtr snapshot,
            [ReadOnly] [NoAlias] IntPtr baseline,
            [NoAlias] [ReadOnly] IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            SerializeCombinedGenerated(
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline),
                changeMaskData, startOffset,
                ref writer, compressionModel);
        }

        /// <inheritdoc cref="IGhostSerializer.Serialize"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Serialize([ReadOnly] [NoAlias] IntPtr snapshot,
            [ReadOnly] [NoAlias] IntPtr baseline,
            [NoAlias] [ReadOnly] IntPtr changeMaskData, int startOffset,
            ref DataStreamWriter writer, in StreamCompressionModel compressionModel)
        {
            SerializeGenerated(
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline),
                changeMaskData, startOffset,
                ref writer, compressionModel);
        }

        /// <inheritdoc cref="IGhostSerializer.Deserialize"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Deserialize(ref DataStreamReader reader, in StreamCompressionModel compressionModel,
            IntPtr changeMask,
            int startOffset, [NoAlias]IntPtr snapshot, [NoAlias][ReadOnly]IntPtr baseline)

        {
            DeserializeGenerated(ref reader, compressionModel, changeMask, startOffset,
                ref GhostComponentSerializer.TypeCast<Snapshot>(snapshot),
                ref GhostComponentSerializer.TypeCast<Snapshot>(baseline));
        }

        /// <inheritdoc cref="IGhostSerializer.Deserialize"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void RestoreFromBackup([NoAlias] IntPtr component, [NoAlias] [ReadOnly] IntPtr backup)
        {
            RestoreFromBackupGenerated(
                ref GhostComponentSerializer.TypeCast<Unity.NetCode.InputBufferData<PlayerInput>>(component),
                ref GhostComponentSerializer.TypeCast<Unity.NetCode.InputBufferData<PlayerInput>>(backup));
        }

#if UNITY_EDITOR || NETCODE_DEBUG
        /// <inheritdoc cref="IGhostSerializer{TComponent,TSnapshot}.ReportPredictionErrorsGenerated"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void ReportPredictionErrors([NoAlias][ReadOnly]IntPtr component, [NoAlias][ReadOnly]IntPtr backup, IntPtr errorsList,
            int errorsCount)
        {
            ReportPredictionErrorsGenerated(GhostComponentSerializer.TypeCast<Unity.NetCode.InputBufferData<PlayerInput>>(component),
                GhostComponentSerializer.TypeCast<Unity.NetCode.InputBufferData<PlayerInput>>(backup), errorsList, errorsCount);
        }
#endif
    }

    //Registration
    [BurstCompile]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial struct Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer : IGhostSerializer
    {
        static internal GhostComponentSerializer.State GetState(ref SystemState state)
        {
            // This needs to be lazy initialized because otherwise there is a depenency on the static initialization order which breaks il2cpp builds, due to TypeManager not being initialized yet.
            // Also, Burst function pointer compilation can take a while.
            if (!s_StateInitialized)
            {
                s_State = new GhostComponentSerializer.State
                {
                    GhostFieldsHash = 6359459209182528361,
                    ComponentType = ComponentType.ReadWrite<Unity.NetCode.InputBufferData<PlayerInput>>(),
                    ComponentSize = UnsafeUtility.SizeOf<Unity.NetCode.InputBufferData<PlayerInput>>(),
#if COMPONENT_HAS_GHOST_FIELDS
                    SnapshotSize = UnsafeUtility.SizeOf<Snapshot>(),
#else
                    SnapshotSize = 0,
#endif
                    ChangeMaskBits = 10,
                    PrefabType = GhostPrefabType.AllPredicted,
                    SendMask = GhostSendType.OnlyPredictedClients,
                    SendToOwner = SendToOwnerType.SendToNonOwner,
                    VariantHash = 1372260904184580062,
                    SerializationStrategyIndex = -1,
                    SerializesEnabledBit = 0,
#if UNITY_EDITOR || NETCODE_DEBUG
                    ProfilerMarker = new Unity.Profiling.ProfilerMarker("Unity.NetCode.InputBufferData<PlayerInput>"),
                    VariantTypeFullNameHash = TypeHash.FNV1A64("Unity.NetCode.InputBufferData`1[[PlayerInput, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]")
#endif
                };
                // UnsafeUtility.SizeOf<T> reports 1 with zero-sized components.
                if (s_State.ComponentType.IsZeroSized)
                    s_State.ComponentSize = 0;

#if UNITY_EDITOR || NETCODE_DEBUG
                s_State.ProfilerMarker.Begin();
                var innerMarker = new Unity.Profiling.ProfilerMarker("Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferData");
                innerMarker.Begin();
#endif
                s_StateInitialized = SetupFunctionPointers(ref s_State, ref state);
                //TODO: DOTS-7926 we should understand why we have in some cases a StackOverflowException.
                //UNCOMMENT THIS LINE TO DEBUG IF A BIG COMPONENT MAY BE CAUSING A STACK OVERFLOW
                // const int maxSizeToAvoidStackOverflow = 4_500;
                // if (s_State.ComponentSize > maxSizeToAvoidStackOverflow)
                // {
                //     UnityEngine.Debug.LogWarning($"The type '{s_State.ComponentType}' is very large ({s_State.ComponentSize} bytes)! There is a risk of StackOverflowExceptions in the Serializers at roughly {maxSizeToAvoidStackOverflow} bytes! Remove large fields.");
                // }
#if UNITY_EDITOR || NETCODE_DEBUG
                s_State.NumPredictionErrors = GetPredictionErrorNamesGenerated(ref s_State.PredictionErrorNames);
#endif

#if UNITY_EDITOR || NETCODE_DEBUG
                innerMarker.End();
                s_State.ProfilerMarker.End();
#endif
            }
            return s_State;
        }

        private static bool s_StateInitialized;
        private static GhostComponentSerializer.State s_State;

        private static bool SetupFunctionPointers(ref GhostComponentSerializer.State state,
            ref SystemState systemState)
        {
            // Optimization: Creating burst functions is expensive.
            // We don't need to do it in literally any other words as they're never called.
            if ((systemState.WorldUnmanaged.Flags & WorldFlags.GameServer) != WorldFlags.GameServer
                && (systemState.WorldUnmanaged.Flags & WorldFlags.GameClient) != WorldFlags.GameClient
                && (systemState.WorldUnmanaged.Flags & WorldFlags.GameThinClient) != WorldFlags.GameThinClient)
                return false;

#if !GHOST_COMPONENT_IS_BUFFER
            state.PostSerialize = new PortableFunctionPointer<GhostComponentSerializer.PostSerializeDelegate>(
                AOT_PostSerialize);
            state.Serialize = new PortableFunctionPointer<GhostComponentSerializer.SerializeDelegate>(
                AOT_Serialize);
#else
            state.PostSerializeBuffer = new PortableFunctionPointer<GhostComponentSerializer.PostSerializeBufferDelegate>(
                AOT_PostSerializeBuffer);
            state.SerializeBuffer = new PortableFunctionPointer<GhostComponentSerializer.SerializeBufferDelegate>(
                AOT_SerializeBuffer);
#endif
            state.CopyFromSnapshot = new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(
                AOT_CopyFromSnapshot);
            state.CopyToSnapshot = new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(
                AOT_CopyToSnapshot);
            state.RestoreFromBackup = new PortableFunctionPointer<GhostComponentSerializer.RestoreFromBackupDelegate>(
                AOT_RestoreFromBackup);
            state.PredictDelta = new PortableFunctionPointer<GhostComponentSerializer.PredictDeltaDelegate>(
                AOT_PredictDelta);
            state.Deserialize = new PortableFunctionPointer<GhostComponentSerializer.DeserializeDelegate>(
                AOT_Deserialize);
#if UNITY_EDITOR || NETCODE_DEBUG
            state.ReportPredictionErrors = new PortableFunctionPointer<GhostComponentSerializer.ReportPredictionErrorsDelegate>(
                AOT_ReportPredictionErrors);
#endif
            return true;
        }

#if !GHOST_COMPONENT_IS_BUFFER
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.PostSerializeDelegate))]
        private static void AOT_PostSerialize(IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            int maskOffsetInBits,
            int count, IntPtr baselines, ref DataStreamWriter writer,
            ref StreamCompressionModel compressionModel,
            IntPtr entityStartBit)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer);
            Unity.NetCode.ComponentSerializationHelper<
                    Unity.NetCode.InputBufferData<PlayerInput>,
                    Snapshot,
                    Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer
            >.PostSerializeComponents(serializer,
                snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, count, baselines,
                ref writer, ref compressionModel, entityStartBit);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void AOT_Serialize([NoAlias]IntPtr stateData,
            IntPtr snapshotData, int snapshotOffset, int snapshotStride, int maskOffsetInBits,
            IntPtr componentData, int count, IntPtr baselines,
            ref DataStreamWriter writer, ref StreamCompressionModel compressionModel, IntPtr entityStartBit)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer);
            Unity.NetCode.ComponentSerializationHelper<
                    Unity.NetCode.InputBufferData<PlayerInput>,
                    Snapshot,
                    Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer
            >.SerializeComponents(serializer, stateData, snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, componentData, count, baselines, ref writer, compressionModel, entityStartBit);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
#else
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.PostSerializeDelegate))]
        private static void AOT_PostSerializeBuffer(IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            int maskOffsetInBits, int changeMaskBits, int count, IntPtr baselines,
            ref DataStreamWriter writer, ref StreamCompressionModel compressionModel,
            IntPtr entityStartBit, IntPtr snapshotDynamicDataPtr, IntPtr dynamicSizePerEntity, int dynamicSnapshotMaxOffset)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer);
            Unity.NetCode.BufferSerializationHelper<
                Unity.NetCode.InputBufferData<PlayerInput>,
                Snapshot,
                Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer
            >.PostSerializeBuffers(snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, changeMaskBits, count, baselines,
                ref writer, compressionModel, entityStartBit, snapshotDynamicDataPtr, dynamicSizePerEntity, dynamicSnapshotMaxOffset,
                serializer);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void AOT_SerializeBuffer(IntPtr stateData,
            IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            int maskOffsetInBits, int changeMaskBits,
            IntPtr componentData, IntPtr componentDataLen, int count, [NoAlias]IntPtr baselines,
            ref DataStreamWriter writer, ref StreamCompressionModel compressionModel,
            IntPtr entityStartBit, IntPtr snapshotDynamicDataPtr, ref int dynamicSnapshotDataOffset,
            IntPtr dynamicSizePerEntity, int dynamicSnapshotMaxOffset)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer);
            Unity.NetCode.BufferSerializationHelper<
                Unity.NetCode.InputBufferData<PlayerInput>,
                Snapshot,
                Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer
            >.SerializeBuffers(stateData, snapshotData, snapshotOffset, snapshotStride, maskOffsetInBits, changeMaskBits,
                componentData, componentDataLen, count, baselines, ref writer, compressionModel, entityStartBit, snapshotDynamicDataPtr,
                ref dynamicSnapshotDataOffset, dynamicSizePerEntity, dynamicSnapshotMaxOffset, serializer);
#else
            GhostComponentSerializer.ResetEntityStartBits(count, ref writer, entityStartBit);
#endif
        }
#endif
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void AOT_CopyToSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride,
            IntPtr componentData, int componentStride, int count)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer);
#if !GHOST_COMPONENT_IS_BUFFER
            Unity.NetCode.ComponentSerializationHelper<
                    Unity.NetCode.InputBufferData<PlayerInput>,
                    Snapshot,
                    Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer
            >.CopyComponentsToSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#else
            Unity.NetCode.BufferSerializationHelper<
                Unity.NetCode.InputBufferData<PlayerInput>,
                Snapshot,
                Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer
            >.CopyBuffersToSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#endif
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void AOT_CopyFromSnapshot(IntPtr stateData, IntPtr snapshotData,
            int snapshotOffset, int snapshotStride,
            IntPtr componentData, int componentStride, int count)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer);
#if !GHOST_COMPONENT_IS_BUFFER
            Unity.NetCode.ComponentSerializationHelper<
                Unity.NetCode.InputBufferData<PlayerInput>,
                Snapshot,
                Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer
            >.CopyComponentsFromSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#else
            Unity.NetCode.BufferSerializationHelper<
                Unity.NetCode.InputBufferData<PlayerInput>,
                Snapshot,
                Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer
            >.CopyBuffersFromSnapshot(stateData, snapshotData, snapshotOffset, snapshotStride, componentData, componentStride, count, serializer);
#endif
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.RestoreFromBackupDelegate))]
        private static void AOT_RestoreFromBackup(IntPtr componentData, IntPtr backupData)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer);
            serializer.RestoreFromBackup(componentData, backupData);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.PredictDeltaDelegate))]
        private static void AOT_PredictDelta(IntPtr snapshotData,
            IntPtr baseline1Data, IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer);
            serializer.PredictDelta(snapshotData, baseline1Data, baseline2Data, ref predictor);
#endif
        }
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.DeserializeDelegate))]
        private static void AOT_Deserialize(IntPtr snapshotData, IntPtr baselineData,
            ref DataStreamReader reader, ref StreamCompressionModel compressionModel,
            IntPtr changeMaskData, int startOffset)
        {
#if COMPONENT_HAS_GHOST_FIELDS
            var serializer = default(Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer);
            serializer.Deserialize(ref reader, compressionModel, changeMaskData, startOffset, snapshotData, baselineData);
#endif
        }
#if UNITY_EDITOR || NETCODE_DEBUG
        [BurstCompile(DisableDirectCall = true)]
        [AOT.MonoPInvokeCallback(typeof(GhostComponentSerializer.ReportPredictionErrorsDelegate))]
        private static void AOT_ReportPredictionErrors(IntPtr componentData, IntPtr backupData,
            IntPtr errorsList, int errorsCount)
        {
            var serializer = default(Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer);
            serializer.ReportPredictionErrors(componentData, backupData, errorsList, errorsCount);
        }
#endif
    }
}
