#line 1 "#templateid:NetCode.GhostFixedListElement.cs
namespace __GHOST_NAMESPACE__
{
    /// <summary>
    /// Auto-Generated struct used to represent composite (struct) fixed array argument.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal struct __GHOST_FIELD_TYPE__
    {
        #region __GHOST_FIELD__
        #endregion
    }
}
/Temp/NetCodeGenerated/Assembly-CSharp/GhostComponentSerializerCollection.cs"

// THIS FILE IS AUTO-GENERATED BY NETCODE PACKAGE SOURCE GENERATORS. DO NOT DELETE, MOVE, COPY, MODIFY, OR COMMIT THIS FILE.
// TO MAKE CHANGES TO THE SERIALIZATION OF A TYPE, REFER TO THE MANUAL.
using System.Text;
using Unity.Entities;
using Unity.Burst;
using Unity.Collections;
using Unity.NetCode;
using Unity.NetCode.LowLevel;
using Unity.NetCode.LowLevel.Unsafe;
using Assembly_CSharp.Generated;

namespace Assembly_CSharp.Generated
{
    /// <summary>
    /// GhostComponentSerializerRegreationSystem
    /// </summary>
    [BurstCompile]
    [System.Runtime.CompilerServices.CompilerGenerated]
    [UpdateInGroup(typeof(GhostComponentSerializerCollectionSystemGroup))]
    [CreateAfter(typeof(GhostComponentSerializerCollectionSystemGroup))]
    [CreateBefore(typeof(DefaultVariantSystemGroup))]
    [BakingVersion(true)]
    public partial struct GhostComponentSerializerRegistrationSystem : ISystem, IGhostComponentSerializerRegistration
    {
        /// <summary>TODO - Not currently burst compiled due to statics in GhostComponentSerializer.State.</summary>
        /// <inheritdoc/>
        public void OnCreate(ref SystemState state)
        {
            // Manual query as `SystemAPI.GetSingletonRW<GhostComponentSerializerCollectionData>()` is throwing "fail to compile" errors.
            using var builder = new EntityQueryBuilder(Allocator.Temp).WithAllRW<GhostComponentSerializerCollectionData>();
            using var query = state.EntityManager.CreateEntityQuery(builder);
            ref var data = ref query.GetSingletonRW<GhostComponentSerializerCollectionData>().ValueRW;

            ComponentTypeSerializationStrategy ss = default;
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "EquipmentEventCounter",
                Component = ComponentType.ReadWrite<EquipmentEventCounter>(),
                Hash = 14612184081469316452,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 1,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "Unity.NetCode.InputBufferData<EquipmentEventCounter>",
                Component = ComponentType.ReadWrite<Unity.NetCode.InputBufferData<EquipmentEventCounter>>(),
                Hash = 6777218569586255164,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 1,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 1,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "ChunkEventCounter",
                Component = ComponentType.ReadWrite<ChunkEventCounter>(),
                Hash = 14643081367316806170,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.AllPredicted,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 1,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "Unity.NetCode.InputBufferData<ChunkEventCounter>",
                Component = ComponentType.ReadWrite<Unity.NetCode.InputBufferData<ChunkEventCounter>>(),
                Hash = 8020427409600729298,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.AllPredicted,
                SendTypeOptimization = GhostSendType.OnlyPredictedClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 1,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 1,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "PlayerInput",
                Component = ComponentType.ReadWrite<PlayerInput>(),
                Hash = 1660363348196260094,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.AllPredicted,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 1,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "Unity.NetCode.InputBufferData<PlayerInput>",
                Component = ComponentType.ReadWrite<Unity.NetCode.InputBufferData<PlayerInput>>(),
                Hash = 1372260904184580062,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.AllPredicted,
                SendTypeOptimization = GhostSendType.OnlyPredictedClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 1,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 1,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "EquipmentEventBuffer",
                Component = ComponentType.ReadWrite<EquipmentEventBuffer>(),
                Hash = 8390267636598729308,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "InventorySlot",
                Component = ComponentType.ReadWrite<InventorySlot>(),
                Hash = 1979490110839945148,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "ChunkComponent",
                Component = ComponentType.ReadWrite<ChunkComponent>(),
                Hash = 13647115872473700180,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "ChunkTiles",
                Component = ComponentType.ReadWrite<ChunkTiles>(),
                Hash = 13590023896616619412,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "BuildingObjects",
                Component = ComponentType.ReadWrite<BuildingObjects>(),
                Hash = 13954076973311546972,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "Bullet",
                Component = ComponentType.ReadWrite<Bullet>(),
                Hash = 10237261704927524668,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "ChunkEvents",
                Component = ComponentType.ReadWrite<ChunkEvents>(),
                Hash = 5138059294602664420,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "PlayerInputSync",
                Component = ComponentType.ReadWrite<PlayerInputSync>(),
                Hash = 1477304182100489188,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "PlayerLook",
                Component = ComponentType.ReadWrite<PlayerLook>(),
                Hash = 8588563645738447812,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "Player",
                Component = ComponentType.ReadWrite<Player>(),
                Hash = 4086804167088025962,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "Health",
                Component = ComponentType.ReadWrite<Health>(),
                Hash = 6749673601174228756,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "Hunger",
                Component = ComponentType.ReadWrite<Hunger>(),
                Hash = 6464840122227270874,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "Thirst",
                Component = ComponentType.ReadWrite<Thirst>(),
                Hash = 16918806573181528252,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "AimRotation",
                Component = ComponentType.ReadWrite<AimRotation>(),
                Hash = 2564297717026188718,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "Cooldown",
                Component = ComponentType.ReadWrite<Cooldown>(),
                Hash = 15176954909896060782,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.OnlyPredictedClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "ContainerComponent",
                Component = ComponentType.ReadWrite<ContainerComponent>(),
                Hash = 686507675498549308,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "LinkedContainers",
                Component = ComponentType.ReadWrite<LinkedContainers>(),
                Hash = 18134272274485239454,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "CurrentHitPoints",
                Component = ComponentType.ReadWrite<CurrentHitPoints>(),
                Hash = 13772156756796214154,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "DamageBufferElement",
                Component = ComponentType.ReadWrite<DamageBufferElement>(),
                Hash = 9368049711182361902,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.AllPredicted,
                SendTypeOptimization = GhostSendType.OnlyPredictedClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "DamageThisTick",
                Component = ComponentType.ReadWrite<DamageThisTick>(),
                Hash = 14384030980968956764,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.AllPredicted,
                SendTypeOptimization = GhostSendType.OnlyPredictedClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 1,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "DestroyAtTick",
                Component = ComponentType.ReadWrite<DestroyAtTick>(),
                Hash = 17468429233636012820,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);
            ss = new ComponentTypeSerializationStrategy
            {
                DisplayName = "ItemBarData",
                Component = ComponentType.ReadWrite<ItemBarData>(),
                Hash = 16658401302825848676,
                SelfIndex = -1,
                SerializerIndex = -1,
                PrefabType = GhostPrefabType.All,
                SendTypeOptimization = GhostSendType.AllClients,
                SendForChildEntities = 0,
                IsDefaultSerializer = 1,
                IsInputComponent = 0,
                IsInputBuffer = 0,
                IsTestVariant = 0,
                HasDontSupportPrefabOverridesAttribute = 0,
            };
            data.AddSerializationStrategy(ref ss);

            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_EquipmentEventCounterEquipmentEventCounterInputBufferDataGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_ChunkEventCounterChunkEventCounterInputBufferDataGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_PlayerInputPlayerInputInputBufferDataGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_EquipmentEventBufferGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_InventorySlotGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_ChunkComponentGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_ChunkTilesGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_BuildingObjectsGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_ChunkEventsGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_PlayerInputSyncGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_PlayerLookGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_PlayerGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_HealthGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_HungerGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_ThirstGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_AimRotationGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_ContainerComponentGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_LinkedContainersGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_CurrentHitPointsGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_DestroyAtTickGhostComponentSerializer.GetState(ref state));
            data.AddSerializer(global::Assembly_CSharp_Generated.Assembly_CSharp_Generated_ItemBarDataGhostComponentSerializer.GetState(ref state));

            data.AddInputComponent(ComponentType.ReadWrite<EquipmentEventCounter>(), ComponentType.ReadWrite<Unity.NetCode.InputBufferData<EquipmentEventCounter>>());
            data.AddInputComponent(ComponentType.ReadWrite<ChunkEventCounter>(), ComponentType.ReadWrite<Unity.NetCode.InputBufferData<ChunkEventCounter>>());
            data.AddInputComponent(ComponentType.ReadWrite<PlayerInput>(), ComponentType.ReadWrite<Unity.NetCode.InputBufferData<PlayerInput>>());
        }

        /// <summary>Ignore. Disables the system.</summary>
        /// <inheritdoc/>
        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            state.Enabled = false;
        }
    }
}
